# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entrance rig_hash set value 'c7ae365e91ac3598021444d0ba54f3533ae209d39e93d5c5119e6185e43f79cb'
scoreboard objectives add aj.init.frame dummy
scoreboard objectives add aj.close.frame dummy
scoreboard objectives add aj.leave.frame dummy