# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entrance rig_hash set value '077935f8bc485c8acc6b682cbd4ab0cde06d9a461f370581b48593c110bd661e'
scoreboard objectives add aj.init.frame dummy
scoreboard objectives add aj.close.frame dummy