# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4997f,-0.0183f,0.0009f,-0.0321f,-0.0182f,0.4993f,0.0183f,0.8715f,-0.0016f,0.0183f,-0.4997f,0.0944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4997f,-0.0183f,0.0009f,-0.0287f,-0.0182f,0.4993f,0.0183f,0.7779f,-0.0016f,0.0183f,-0.4997f,0.091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4997f,-0.0183f,0.0009f,-0.0286f,-0.0182f,0.4993f,0.0183f,0.7803f,-0.0016f,0.0183f,-0.4997f,0.0259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4997f,-0.0183f,0.0009f,-0.0194f,-0.0182f,0.4993f,0.0183f,0.5305f,-0.0016f,0.0183f,-0.4997f,0.0194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4997f,-0.0183f,0.0009f,-0.0114f,-0.0182f,0.4993f,0.0183f,0.3121f,-0.0016f,0.0183f,-0.4997f,0.0114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4997f,-0.0183f,0.0009f,0f,-0.0182f,0.4993f,0.0183f,0f,-0.0016f,0.0183f,-0.4997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.1063615278,"rx":2.0981435329},"locator":{"px":-0.0314397362,"py":0.8311812251,"pz":0.3431029387,"ry":0.1063615278,"rx":2.0981435329}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args