# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.4997f,-0.0183f,0.0009f,0f,-0.0182f,0.4993f,0.0183f,0f,-0.0016f,0.0183f,-0.4997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.1063615278,"rx":2.0981435329}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args