# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0091f,-0.0051f,0.4999f,0.0051f,0.8743f,-0.0005f,0.0051f,-0.5f,0.0714f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0081f,-0.0051f,0.4999f,0.0051f,0.7805f,-0.0005f,0.0051f,-0.5f,0.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5f,-0.0051f,0.0004f,-0.008f,-0.0051f,0.4999f,0.0051f,0.7812f,-0.0005f,0.0051f,-0.5f,0.0053f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0055f,-0.0051f,0.4999f,0.0051f,0.5312f,-0.0005f,0.0051f,-0.5f,0.0054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0032f,-0.0051f,0.4999f,0.0051f,0.3125f,-0.0005f,0.0051f,-0.5f,0.0032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5f,-0.0051f,0.0004f,0f,-0.0051f,0.4999f,0.0051f,0f,-0.0005f,0.0051f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.0456405404,"rx":0.5824455295},"locator":{"px":-0.0089294012,"py":0.8404851303,"pz":0.3210534598,"ry":0.0456405404,"rx":0.5824455295}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args