# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.4998f,0.0122f,-0.0014f,0f,0.0122f,0.4997f,-0.0124f,0f,0.0011f,-0.0124f,-0.4998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.8430361526,"rx":-1.4161107888}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args