# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4996f,0.0209f,-0.0027f,0.037f,0.021f,0.4991f,-0.0211f,0.8761f,0.0018f,-0.0212f,-0.4995f,0.0253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4996f,0.0209f,-0.0027f,0.0331f,0.021f,0.4991f,-0.0211f,0.7825f,0.0018f,-0.0212f,-0.4995f,0.0292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4996f,0.0209f,-0.0027f,0.0327f,0.021f,0.4991f,-0.0211f,0.7797f,0.0018f,-0.0212f,-0.4995f,-0.0358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4996f,0.0209f,-0.0027f,0.0222f,0.021f,0.4991f,-0.0211f,0.5303f,0.0018f,-0.0212f,-0.4995f,-0.0226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4996f,0.0209f,-0.0027f,0.0131f,0.021f,0.4991f,-0.0211f,0.3119f,0.0018f,-0.0212f,-0.4995f,-0.0133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4996f,0.0209f,-0.0027f,0f,0.021f,0.4991f,-0.0211f,0f,0.0018f,-0.0212f,-0.4995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.6871389982,"rx":-2.4241336059},"locator":{"px":0.0370337493,"py":0.8554650921,"pz":0.2763662247,"ry":359.6871389982,"rx":-2.4241336059}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args