# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4983f,0.0405f,-0.0069f,0.0717f,0.0409f,0.4967f,-0.0408f,0.8742f,0.0036f,-0.0412f,-0.4983f,-0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4983f,0.0405f,-0.0069f,0.0641f,0.0409f,0.4967f,-0.0408f,0.7811f,0.0036f,-0.0412f,-0.4983f,-0.0021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4983f,0.0405f,-0.0069f,0.0632f,0.0409f,0.4967f,-0.0408f,0.7758f,0.0036f,-0.0412f,-0.4983f,-0.067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4983f,0.0405f,-0.0069f,0.043f,0.0409f,0.4967f,-0.0408f,0.5277f,0.0036f,-0.0412f,-0.4983f,-0.0438f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4983f,0.0405f,-0.0069f,0.0253f,0.0409f,0.4967f,-0.0408f,0.3104f,0.0036f,-0.0412f,-0.4983f,-0.0258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4983f,0.0405f,-0.0069f,0f,0.0409f,0.4967f,-0.0408f,0f,0.0036f,-0.0412f,-0.4983f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.2034421898,"rx":-4.6805803554},"locator":{"px":0.0726379341,"py":0.8635977463,"pz":0.241853211,"ry":359.2034421898,"rx":-4.6805803554}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args