# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.4999f,-0.0071f,0.0005f,0f,-0.0071f,0.4999f,0.0072f,0f,-0.0006f,0.0072f,-0.4999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.0596973322,"rx":0.8216570184}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args