# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4981f,0.0429f,-0.0076f,0.076f,0.0434f,0.4962f,-0.0432f,0.8738f,0.0038f,-0.0437f,-0.4981f,-0.0142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4981f,0.0429f,-0.0076f,0.0679f,0.0434f,0.4962f,-0.0432f,0.7808f,0.0038f,-0.0437f,-0.4981f,-0.006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4981f,0.0429f,-0.0076f,0.067f,0.0434f,0.4962f,-0.0432f,0.7751f,0.0038f,-0.0437f,-0.4981f,-0.0709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4981f,0.0429f,-0.0076f,0.0456f,0.0434f,0.4962f,-0.0432f,0.5273f,0.0038f,-0.0437f,-0.4981f,-0.0464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4981f,0.0429f,-0.0076f,0.0268f,0.0434f,0.4962f,-0.0432f,0.3101f,0.0038f,-0.0437f,-0.4981f,-0.0273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4981f,0.0429f,-0.0076f,0f,0.0434f,0.4962f,-0.0432f,0f,0.0038f,-0.0437f,-0.4981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"locator":{"px":0.0770719673,"py":0.8644031123,"pz":0.2375657462,"ry":359.1309463362,"rx":-4.956591095}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args