# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.4986f,0.0373f,-0.0061f,0f,0.0377f,0.4972f,-0.0376f,0f,0.0033f,-0.038f,-0.4985f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.2943756114,"rx":-4.3140233684}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args