# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4989f,0.0326f,-0.005f,0.0576f,0.0328f,0.4978f,-0.0328f,0.8753f,0.0029f,-0.0331f,-0.4989f,0.0045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4989f,0.0326f,-0.005f,0.0515f,0.0328f,0.4978f,-0.0328f,0.782f,0.0029f,-0.0331f,-0.4989f,0.0107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4989f,0.0326f,-0.005f,0.0509f,0.0328f,0.4978f,-0.0328f,0.7777f,0.0029f,-0.0331f,-0.4989f,-0.0543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4989f,0.0326f,-0.005f,0.0346f,0.0328f,0.4978f,-0.0328f,0.529f,0.0029f,-0.0331f,-0.4989f,-0.0351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4989f,0.0326f,-0.005f,0.0204f,0.0328f,0.4978f,-0.0328f,0.3112f,0.0029f,-0.0331f,-0.4989f,-0.0207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4989f,0.0326f,-0.005f,0f,0.0328f,0.4978f,-0.0328f,0f,0.0029f,-0.0331f,-0.4989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.4222379834,"rx":-3.7627807575},"locator":{"px":0.0581178698,"py":0.8606135966,"pz":0.2560016856,"ry":359.4222379834,"rx":-3.7627807575}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args