# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.4998f,0.0148f,-0.0017f,0f,0.0149f,0.4996f,-0.0149f,0f,0.0013f,-0.015f,-0.4998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.800208864,"rx":-1.7097945977}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args