# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4998f,0.0148f,-0.0017f,0.0262f,0.0149f,0.4996f,-0.0149f,0.8761f,0.0013f,-0.015f,-0.4998f,0.0363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4998f,0.0148f,-0.0017f,0.0234f,0.0149f,0.4996f,-0.0149f,0.7824f,0.0013f,-0.015f,-0.4998f,0.0391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4998f,0.0148f,-0.0017f,0.0231f,0.0149f,0.4996f,-0.0149f,0.7805f,0.0013f,-0.015f,-0.4998f,-0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4998f,0.0148f,-0.0017f,0.0157f,0.0149f,0.4996f,-0.0149f,0.5308f,0.0013f,-0.015f,-0.4998f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4998f,0.0148f,-0.0017f,0.0093f,0.0149f,0.4996f,-0.0149f,0.3122f,0.0013f,-0.015f,-0.4998f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4998f,0.0148f,-0.0017f,0f,0.0149f,0.4996f,-0.0149f,0f,0.0013f,-0.015f,-0.4998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.800208864,"rx":-1.7097945977},"locator":{"px":0.0260952608,"py":0.8523253637,"pz":0.2871076876,"ry":359.800208864,"rx":-1.7097945977}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args