# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0311f,-0.0177f,0.4994f,0.0178f,0.8717f,-0.0015f,0.0177f,-0.4997f,0.0935f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0278f,-0.0177f,0.4994f,0.0178f,0.778f,-0.0015f,0.0177f,-0.4997f,0.0901f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0276f,-0.0177f,0.4994f,0.0178f,0.7804f,-0.0015f,0.0177f,-0.4997f,0.0251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0188f,-0.0177f,0.4994f,0.0178f,0.5306f,-0.0015f,0.0177f,-0.4997f,0.0188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0111f,-0.0177f,0.4994f,0.0178f,0.3121f,-0.0015f,0.0177f,-0.4997f,0.0111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4997f,-0.0177f,0.0009f,0f,-0.0177f,0.4994f,0.0178f,0f,-0.0015f,0.0177f,-0.4997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.1050583984,"rx":2.0359485173},"locator":{"px":-0.0304391457,"py":0.8315888407,"pz":0.3422042824,"ry":0.1050583984,"rx":2.0359485173}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args