# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4996f,-0.0204f,0.0009f,-0.0358f,-0.0203f,0.4992f,0.0205f,0.871f,-0.0018f,0.0204f,-0.4996f,0.0982f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4996f,-0.0204f,0.0009f,-0.032f,-0.0203f,0.4992f,0.0205f,0.7774f,-0.0018f,0.0204f,-0.4996f,0.0943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4996f,-0.0204f,0.0009f,-0.0319f,-0.0203f,0.4992f,0.0205f,0.7801f,-0.0018f,0.0204f,-0.4996f,0.0293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4996f,-0.0204f,0.0009f,-0.0217f,-0.0203f,0.4992f,0.0205f,0.5304f,-0.0018f,0.0204f,-0.4996f,0.0217f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4996f,-0.0204f,0.0009f,-0.0127f,-0.0203f,0.4992f,0.0205f,0.312f,-0.0018f,0.0204f,-0.4996f,0.0128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4996f,-0.0204f,0.0009f,0f,-0.0203f,0.4992f,0.0205f,0f,-0.0018f,0.0204f,-0.4996f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.108453862,"rx":2.3453500676},"locator":{"px":-0.0350039315,"py":0.8295560551,"pz":0.3466724517,"ry":0.108453862,"rx":2.3453500676}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args