# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4995f,-0.0223f,0.0009f,-0.0392f,-0.0223f,0.499f,0.0224f,0.8704f,-0.0019f,0.0223f,-0.4995f,0.1015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4995f,-0.0223f,0.0009f,-0.035f,-0.0223f,0.499f,0.0224f,0.7769f,-0.0019f,0.0223f,-0.4995f,0.0974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4995f,-0.0223f,0.0009f,-0.0349f,-0.0223f,0.499f,0.0224f,0.7798f,-0.0019f,0.0223f,-0.4995f,0.0323f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4995f,-0.0223f,0.0009f,-0.0237f,-0.0223f,0.499f,0.0224f,0.5302f,-0.0019f,0.0223f,-0.4995f,0.0237f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4995f,-0.0223f,0.0009f,-0.014f,-0.0223f,0.499f,0.0224f,0.3119f,-0.0019f,0.0223f,-0.4995f,0.014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4995f,-0.0223f,0.0009f,0f,-0.0223f,0.499f,0.0224f,0f,-0.0019f,0.0223f,-0.4995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.1088524796,"rx":2.5693061537},"locator":{"px":-0.0383009377,"py":0.8280541387,"pz":0.3498995484,"ry":0.1088524796,"rx":2.5693061537}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args