# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.75f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone3) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5625f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone1) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5625f,0f,0f,-1f,-0.0052f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone) { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(bone4) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.625f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(root) { transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }