# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(bone2) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(bone3) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(bone1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(bone) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(bone4) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(root) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i