# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.1412f,0f,0f,-1f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.25f,1f,0f,0f,-1023.1088f,0f,0f,-1f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.25f,-1f,0f,0f,-2047.1088f,0f,0f,-1f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-3070.8588f,0f,0f,-1f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9917f,-0.1288f,-4095.5463f,0f,-0.1288f,-0.9917f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9917f,0.1288f,-5119.5463f,0f,0.1288f,-0.9917f,1.665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":2.2828947144605605e-16,"py":1.3833125000000002,"pz":-1.8641250000000005,"ry":0,"rx":9.5325}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args