# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,-0.0027f,0f,1f,0f,0.3881f,0f,0f,-1f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.2527f,1f,0f,0f,-1023.8619f,0f,0f,-1f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.2473f,-1f,0f,0f,-2047.8619f,0f,0f,-1f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,-0.0027f,0f,1f,0f,-3071.6119f,0f,0f,-1f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.1277f,0f,0.9694f,0.2453f,-4096.2994f,0f,0.2453f,-0.9694f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.1223f,0f,0.9694f,-0.2453f,-5120.2994f,0f,-0.2453f,-0.9694f,2.37f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":1.5867404144640002e-16,"py":1.2915078125000004,"pz":-1.2956718750000005,"ry":0,"rx":7.725937500000003}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args