# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.4475f,0f,0f,-1f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.25f,1f,0f,0f,-1022.8025f,0f,0f,-1f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.25f,-1f,0f,0f,-2046.8025f,0f,0f,-1f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-3070.5525f,0f,0f,-1f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9583f,0.2857f,-4095.24f,0f,0.2857f,-0.9583f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9583f,-0.2857f,-5119.24f,0f,-0.2857f,-0.9583f,-1.155f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":4.664526577102375e-16,"py":2.5844375,"pz":-3.808875,"ry":0,"rx":21.427500000000002}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args