# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,-0.0219f,0f,1f,0f,0.3881f,0f,0f,-1f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.2719f,1f,0f,0f,-1023.8619f,0f,0f,-1f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.2281f,-1f,0f,0f,-2047.8619f,0f,0f,-1f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,-0.0219f,0f,1f,0f,-3071.6119f,0f,0f,-1f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.1469f,0f,0.9917f,0.1288f,-4096.2994f,0f,0.1288f,-0.9917f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.1031f,0f,0.9917f,-0.1288f,-5120.2994f,0f,-0.1288f,-0.9917f,4.015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":3.203131739103191e-17,"py":1.8410925925925925,"pz":-0.26155555555555576,"ry":0,"rx":9.061481481481481}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args