# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0.3519f,0f,1f,0f,1.1412f,0f,0f,-1f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,0.1019f,1f,0f,0f,-1023.1088f,0f,0f,-1f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.6019f,-1f,0f,0f,-2047.1088f,0f,0f,-1f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0.3519f,0f,1f,0f,-3070.8588f,0f,0f,-1f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,0.2269f,0f,0.9694f,-0.2453f,-4095.5463f,0f,-0.2453f,-0.9694f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.4769f,0f,0.9694f,0.2453f,-5119.5463f,0f,0.2453f,-0.9694f,4.72f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-1.5581929620817948e-17,"py":2.3031342592592594,"pz":0.12723611111111133,"ry":0,"rx":11.216481481481482}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args