# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.458f,0f,0f,-1f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.25f,1f,0f,0f,-1022.792f,0f,0f,-1f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.25f,-1f,0f,0f,-2046.792f,0f,0f,-1f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-3070.542f,0f,0f,-1f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9832f,0.1827f,-4095.2295f,0f,0.1827f,-0.9832f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9832f,-0.1827f,-5119.2295f,0f,-0.1827f,-0.9832f,-0.92f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":4.523099006907092e-16,"py":2.5067734375,"pz":-3.693390625,"ry":0,"rx":20.680312500000003}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args