# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0.4781f,0f,1f,0f,1.5104f,0f,0f,-1f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,0.2281f,1f,0f,0f,-1022.7396f,0f,0f,-1f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.7281f,-1f,0f,0f,-2046.7396f,0f,0f,-1f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0.4781f,0f,1f,0f,-3070.4896f,0f,0f,-1f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,0.3531f,0f,0.9063f,-0.4226f,-4095.1771f,0f,-0.4226f,-0.9063f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.6031f,0f,0.9063f,0.4226f,-5119.1771f,0f,0.4226f,-0.9063f,5.425f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-6.463413662166585e-17,"py":2.8634259259259256,"pz":0.5277777777777777,"ry":0,"rx":13.981481481481481}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args