# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0.3688f,0f,1f,0f,1.4667f,0f,0f,-1f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,0.1188f,1f,0f,0f,-1022.7833f,0f,0f,-1f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.6188f,-1f,0f,0f,-2046.7833f,0f,0f,-1f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0.3688f,0f,1f,0f,-3070.5333f,0f,0f,-1f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,0.2438f,0f,0.9694f,-0.2453f,-4095.2208f,0f,-0.2453f,-0.9694f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.4938f,0f,0.9694f,0.2453f,-5119.2208f,0f,0.2453f,-0.9694f,6.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-1.1429866702208753e-16,"py":3.4874675925925924,"pz":0.9333194444444448,"ry":0,"rx":17.14648148148148}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args