# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0.984f,0f,1f,0f,1.4375f,0f,0f,-1f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,0.734f,1f,0f,0f,-1022.8125f,0f,0f,-1f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,1.234f,-1f,0f,0f,-2046.8125f,0f,0f,-1f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0.984f,0f,1f,0f,-3070.5625f,0f,0f,-1f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,0.859f,0f,0.9694f,0.2453f,-4095.25f,0f,0.2453f,-0.9694f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,1.109f,0f,0.9694f,-0.2453f,-5119.25f,0f,-0.2453f,-0.9694f,7.07f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-1.8004178935631468e-16,"py":4.359060185185187,"pz":1.4701527777777788,"ry":0,"rx":21.625740740740753}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args