# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,1.3222f,0f,1f,0f,1.4375f,0f,0f,-1f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,1.0722f,1f,0f,0f,-1022.8125f,0f,0f,-1f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,1.5722f,-1f,0f,0f,-2046.8125f,0f,0f,-1f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,1.3222f,0f,1f,0f,-3070.5625f,0f,0f,-1f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,1.1972f,0f,0.9409f,0.3387f,-4095.25f,0f,0.3387f,-0.9409f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,1.4472f,0f,0.9409f,-0.3387f,-5119.25f,0f,-0.3387f,-0.9409f,7.305f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-1.9618841722340602e-16,"py":4.5755,"pz":1.6020000000000003,"ry":0,"rx":22.740000000000002}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args