# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.016f,0f,1f,0f,1.4375f,0f,0f,-1f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,1.766f,1f,0f,0f,-1022.8125f,0f,0f,-1f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.266f,-1f,0f,0f,-2046.8125f,0f,0f,-1f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.016f,0f,1f,0f,-3070.5625f,0f,0f,-1f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,1.891f,0f,0.9063f,0.4226f,-4095.25f,0f,0.4226f,-0.9063f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.141f,0f,0.9063f,-0.4226f,-5119.25f,0f,-0.4226f,-0.9063f,7.775f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-2.279203765079796e-16,"py":4.997685185185184,"pz":1.8611111111111107,"ry":0,"rx":24.907407407407405}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args