# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.605f,0f,1f,0f,1.4462f,0f,0f,-1f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.355f,1f,0f,0f,-1022.8038f,0f,0f,-1f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.855f,-1f,0f,0f,-2046.8038f,0f,0f,-1f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.605f,0f,1f,0f,-3070.5538f,0f,0f,-1f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.48f,0f,0.9694f,0.2453f,-4095.2413f,0f,0.2453f,-0.9694f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.73f,0f,0.9694f,-0.2453f,-5119.2413f,0f,-0.2453f,-0.9694f,8.48f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-2.736558317611368e-16,"py":5.585060185185185,"pz":2.2345694444444444,"ry":0,"rx":27.88907407407408}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args