# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.5583f,0f,1f,0f,1.5104f,0f,0f,-1f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.3083f,1f,0f,0f,-1022.7396f,0f,0f,-1f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.8083f,-1f,0f,0f,-2046.7396f,0f,0f,-1f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.5583f,0f,1f,0f,-3070.4896f,0f,0f,-1f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.4333f,0f,0.9694f,-0.2453f,-4095.1771f,0f,-0.2453f,-0.9694f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.6833f,0f,0.9694f,0.2453f,-5119.1771f,0f,0.2453f,-0.9694f,9.42f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-3.298739234353288e-16,"py":6.228874999999999,"pz":2.693624999999999,"ry":0,"rx":31.035000000000004}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args