# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.483f,0f,0f,-1f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,-0.25f,1f,0f,0f,-1022.767f,0f,0f,-1f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,0.25f,-1f,0f,0f,-2046.767f,0f,0f,-1f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-3070.517f,0f,0f,-1f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,-0.125f,0f,0.9985f,-0.0545f,-4095.2045f,0f,-0.0545f,-0.9985f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,0.125f,0f,0.9985f,0.0545f,-5119.2045f,0f,0.0545f,-0.9985f,-0.45f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":4.1977639306711033e-16,"py":2.3134765625,"pz":-3.427734375,"ry":0,"rx":18.8671875}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args