# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
title @a[tag=!dead] times 50 50 10
title @a[tag=!dead] title {font:"shader",text:"\uFF00",color:"#0000FF",shadow_color:0}