# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,0.4043f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.25f,1f,0f,0f,-1023.8457f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.75f,-1f,0f,0f,-2047.8457f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,-3071.5957f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.375f,0f,1f,0f,-4096.2832f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.625f,0f,1f,0f,-5120.2832f,0f,0f,-1f,13.65f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-4.643401419817083e-16,"py":6.9391875,"pz":3.791625,"ry":0,"rx":33.04750000000001}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args