# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,1.4375f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.25f,1f,0f,0f,-1022.8125f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.75f,-1f,0f,0f,-2046.8125f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,-3070.5625f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.375f,0f,1f,0f,-4095.25f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.625f,0f,1f,0f,-5119.25f,0f,0f,-1f,16f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-5.185613790139573e-16,"py":6.8828125,"pz":4.234375,"ry":0,"rx":31.562500000000004}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args