# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,2.1412f,0f,0f,-1f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.25f,1f,0f,0f,-1022.1088f,0f,0f,-1f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.75f,-1f,0f,0f,-2046.1088f,0f,0f,-1f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,-3069.8588f,0f,0f,-1f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.375f,0f,0.9694f,0.2453f,-4094.5463f,0f,0.2453f,-0.9694f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.625f,0f,0.9694f,-0.2453f,-5118.5463f,0f,-0.2453f,-0.9694f,16.47f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-5.283269575197182e-16,"py":6.8553014999999995,"pz":4.3141169999999995,"ry":0,"rx":31.178620000000002}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args