# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,2.4375f,0f,0f,-1f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [0f,1f,0f,2.25f,1f,0f,0f,-1021.8125f,0f,0f,-1f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [0f,-1f,0f,2.75f,-1f,0f,0f,-2045.8125f,0f,0f,-1f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-1f,0f,0f,2.5f,0f,1f,0f,-3069.5625f,0f,0f,-1f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-1f,0f,0f,2.375f,0f,0.9299f,0.3677f,-4094.25f,0f,0.3677f,-0.9299f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-1f,0f,0f,2.625f,0f,0.9299f,-0.3677f,-5118.25f,0f,-0.3677f,-0.9299f,21.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-6.098191193341003e-16,"py":6.5635045000000005,"pz":4.979551000000001,"ry":0,"rx":27.557860000000005}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args