# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard players remove @s aj.tween_duration 1
execute if score @s aj.tween_duration matches 1.. run return 1
execute if score @s aj.tween_duration matches 0 run function aj:entity_trap/animations/large_grow/zzz/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.large_grow.frame
function aj:entity_trap/animations/large_grow/zzz/apply_frame with storage animated_java:temp args
execute if score @s aj.large_grow.frame matches 20.. run return run function aj:entity_trap/animations/large_grow/pause
scoreboard players add @s aj.large_grow.frame 1