# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.9911f,-0.5945f,0f,0.1958f,-0.7451f,0.7908f,0f,0f,0f,0f,-1.1981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.2399f,0f,0f,0f,0f,0.7908f,-0.72f,0f,0f,-0.5945f,-0.9577f,0.1958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.9911f,0.5945f,0f,-0.1958f,0.7451f,0.7908f,0f,0f,0f,0f,-1.1981f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.2399f,0f,0f,0f,0f,0.7908f,0.72f,0f,0f,0.5945f,-0.9577f,-0.1958f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8657f,0f,0f,0f,0f,0.8657f,0f,0f,0f,0f,-0.8657f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args