# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.0871f,-0.0048f,0f,0.0015f,-0.0049f,0.0852f,0f,0f,0f,0f,-0.0869f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.0872f,0f,0f,0f,0f,0.0852f,-0.0049f,0f,0f,-0.0048f,-0.0868f,0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.0871f,0.0048f,0f,-0.0015f,0.0049f,0.0852f,0f,0f,0f,0f,-0.0869f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.0872f,0f,0f,0f,0f,0.0852f,0.0049f,0f,0f,0.0048f,-0.0868f,-0.0015f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.0747f,0f,0f,0f,0f,0.0747f,0f,0f,0f,0f,-0.0747f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args