# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:entity_trap"
data modify storage animated_java:temp entry.data.rig_hash set value "e30df68744361bd3e967bfecf10224764469f60e1ddf333677bb2fddb0a577a2"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^0 ^0 {Tags:["aj.entity_trap.bone.root.child","aj.entity_trap.bone.root.child.locator","aj.entity_trap.bone.root.decendant","aj.entity_trap.bone.root.decendant.locator","aj.entity_trap.bone.root.tree","aj.entity_trap.entity","aj.entity_trap.locator","aj.entity_trap.locator.entity_hitbox","aj.entity_trap.node","aj.entity_trap.node.entity_hitbox","aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.entity_hitbox","aj.new","entity.kill_when_reset"]}
execute as @n[ type=minecraft:interaction, tag=aj.entity_trap.locator.entity_hitbox, tag=aj.new, distance=..1 ] run function aj:entity_trap/zzz/summon/as_locator/entity_hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.entity_hitbox set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.entity_hitbox.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_trap.node.petal4] run function aj:entity_trap/zzz/summon/as_node/petal4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.petal4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_trap.node.petal3] run function aj:entity_trap/zzz/summon/as_node/petal3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.petal3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_trap.node.petal2] run function aj:entity_trap/zzz/summon/as_node/petal2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.petal2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_trap.node.petal1] run function aj:entity_trap/zzz/summon/as_node/petal1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.petal1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_trap.node.root] run function aj:entity_trap/zzz/summon/as_node/root
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.root set from storage animated_java:gu out
function aj:entity_trap/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.entity_hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function aj:entity_trap/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:entity_trap/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:entity_trap/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:entity_trap/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:entity_trap/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.entity_hitbox
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount