# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entity_piranha rig_hash set value '9837f930286de28f82d5ae46f9c3a0b6bfb9182528b98164afbd6590993f964b'
scoreboard objectives add aj.small_grow.frame dummy
scoreboard objectives add aj.small_idle.frame dummy
scoreboard objectives add aj.medium_grow.frame dummy
scoreboard objectives add aj.medium_idle.frame dummy
scoreboard objectives add aj.large_grow.frame dummy
scoreboard objectives add aj.large_idle.frame dummy