# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.0469f,-0.0007f,-0.0009f,0.0001f,-0.0011f,0.0285f,0.0372f,0.5602f,0f,0.0372f,-0.0285f,-0.3107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.0469f,-0.0007f,-0.0009f,-0.0001f,-0.0011f,0.0285f,0.0372f,0.5678f,0f,0.0372f,-0.0285f,-0.3055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.0469f,-0.0007f,-0.0009f,0f,-0.0011f,0.0285f,0.0372f,0.5625f,0f,0.0372f,-0.0285f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0000796472,"py":0.5590950608,"pz":-0.302501003,"ry":358.2543775074,"rx":52.4795846943}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args