# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.8948f,0.0463f,0.0604f,-0.0038f,0.0761f,0.5447f,0.7099f,0.5181f,0f,0.7124f,-0.5467f,-0.2783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.8948f,0.0463f,0.0604f,0.0087f,0.0761f,0.5447f,0.7099f,0.6646f,0f,0.7124f,-0.5467f,-0.1789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8948f,0.0463f,0.0604f,0f,0.0761f,0.5447f,0.7099f,0.5625f,0f,0.7124f,-0.5467f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.005531569,"py":0.4974875033,"pz":-0.1209458819,"ry":6.3047726338,"rx":52.2319938346}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args