# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9194f,0.041f,0.0534f,-0.0033f,0.0673f,0.5597f,0.7294f,0.5169f,0f,0.7314f,-0.5612f,-0.2774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9194f,0.041f,0.0534f,0.0077f,0.0673f,0.5597f,0.7294f,0.6674f,0f,0.7314f,-0.5612f,-0.1754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9194f,0.041f,0.0534f,0f,0.0673f,0.5597f,0.7294f,0.5625f,0f,0.7314f,-0.5612f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0048905064,"py":0.49569665,"pz":-0.1158530595,"ry":5.4354003847,"rx":52.3011608684}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args