# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9405f,0.0328f,0.0428f,-0.0027f,0.0539f,0.5725f,0.7461f,0.5159f,0f,0.7473f,-0.5735f,-0.2767f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9405f,0.0328f,0.0428f,0.0062f,0.0539f,0.5725f,0.7461f,0.6698f,0f,0.7473f,-0.5735f,-0.1724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9405f,0.0328f,0.0428f,0f,0.0539f,0.5725f,0.7461f,0.5625f,0f,0.7473f,-0.5735f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0039175724,"py":0.4941678322,"pz":-0.1115601568,"ry":4.2659707564,"rx":52.3777570521}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args