# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.1098f,-0.004f,-0.0052f,0.0003f,-0.0066f,0.0668f,0.0871f,0.5571f,0f,0.0873f,-0.067f,-0.3083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.1098f,-0.004f,-0.0052f,-0.0007f,-0.0066f,0.0668f,0.0871f,0.575f,0f,0.0873f,-0.067f,-0.2961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.1098f,-0.004f,-0.0052f,0f,-0.0066f,0.0668f,0.0871f,0.5625f,0f,0.0873f,-0.067f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0004767878,"py":0.554521791,"pz":-0.2890356871,"ry":355.5545572459,"rx":52.3672192184}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args