# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.3563f,-0.0286f,-0.0372f,0.0023f,-0.0469f,0.2169f,0.2827f,0.5448f,0f,0.2851f,-0.2188f,-0.2988f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.3563f,-0.0286f,-0.0372f,-0.0054f,-0.0469f,0.2169f,0.2827f,0.6032f,0f,0.2851f,-0.2188f,-0.259f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.3563f,-0.0286f,-0.0372f,0f,-0.0469f,0.2169f,0.2827f,0.5625f,0f,0.2851f,-0.2188f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0034082575,"py":0.5366117144,"pz":-0.2358410232,"ry":350.3461051742,"rx":51.8657555568}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args