# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.447f,-0.0315f,-0.0411f,0.0026f,-0.0518f,0.2721f,0.3546f,0.5403f,0f,0.357f,-0.2739f,-0.2954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.447f,-0.0315f,-0.0411f,-0.0059f,-0.0518f,0.2721f,0.3546f,0.6135f,0f,0.357f,-0.2739f,-0.2456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.447f,-0.0315f,-0.0411f,0f,-0.0518f,0.2721f,0.3546f,0.5625f,0f,0.357f,-0.2739f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0037641411,"py":0.5300210368,"pz":-0.216509629,"ry":351.467399673,"rx":52.0062977402}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args