# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.5362f,-0.0278f,-0.0363f,0.0023f,-0.0457f,0.3264f,0.4254f,0.5359f,0f,0.4269f,-0.3276f,-0.292f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.5362f,-0.0278f,-0.0363f,-0.0052f,-0.0457f,0.3264f,0.4254f,0.6237f,0f,0.4269f,-0.3276f,-0.2325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5362f,-0.0278f,-0.0363f,0f,-0.0457f,0.3264f,0.4254f,0.5625f,0f,0.4269f,-0.3276f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0033234951,"py":0.5235421122,"pz":-0.1977115147,"ry":353.6787918118,"rx":52.2305850265}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args