# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.6919f,-0.0013f,-0.0017f,0.0001f,-0.0022f,0.4212f,0.5489f,0.5282f,0f,0.5489f,-0.4212f,-0.2862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.6919f,-0.0013f,-0.0017f,-0.0003f,-0.0022f,0.4212f,0.5489f,0.6415f,0f,0.5489f,-0.4212f,-0.2096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6919f,-0.0013f,-0.0017f,0f,-0.0022f,0.4212f,0.5489f,0.5625f,0f,0.5489f,-0.4212f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0001598737,"py":0.5122296042,"pz":-0.1649148046,"ry":359.7625335798,"rx":52.4996223961}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args