# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(ray) positioned ^0 ^0.4898414273 ^-0.0991880645 rotated ~0 ~52.5 run function aj:entity_camera/animations/grow/zzz/frames/21_locator_ray
execute run function aj:entity_camera/animations/grow/zzz/frames/21_function_keyframe