# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/read with storage animated_java:temp args
function aj:entity_sapling/animations/pause_all
scoreboard players set @s aj.small_idle.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:entity_sapling/animations/small_idle/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only