# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/read with storage animated_java:temp args
function aj:vine_wall/animations/pause_all
tag @s add aj.vine_wall.animation.reset.playing
scoreboard players set @s aj.reset.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:vine_wall/animations/reset/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only