# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:entity_piranha/animations/medium_grow/play
scoreboard players set @s entity.growth 0
scoreboard players reset @s entity.should_grow