# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-1f,0.0066f,-0.0006f,0f,0.0066f,1f,-0.0068f,0f,0.0006f,-0.0068f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.9644791709,"rx":-0.3910586251}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args