# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(root) {transformation: [-0.9985f,0.054f,-0.0077f,0f,0.0543f,0.997f,-0.0544f,0f,0.0047f,-0.0547f,-0.9985f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.5579515231,"rx":-3.1156393951}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args