# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(petal3) { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(petal2) { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(petal1) { transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f], start_interpolation: -1 }
$data merge entity $(root) { transformation: [-1.1667f,0f,0f,0f,0f,1.1667f,0f,0f,0f,0f,-1.1667f,0f,0f,0f,0f,1f], start_interpolation: -1 }