# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$tp $(uuid) ^0 ^0.4898414273 ^-0.0991880645 ~0 ~52.5
data modify storage animated_java:temp entry.data.locators.ray merge value { px: 0, py: 0.4898414273, pz: -0.0991880645, ry: 0, rx: 52.5 }