# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:entity_camera"
data modify storage animated_java:temp entry.data.rig_hash set value "b4a78b3462edf387705848db62e9240b843ec5580e26dea12703d9fe45d0dc4e"
tp @s ~ ~ ~ ~ ~
summon minecraft:item_display ^0 ^0.4898414273 ^-0.0991880645 {Tags:["aj.entity_camera.bone.camera.child","aj.entity_camera.bone.camera.child.locator","aj.entity_camera.bone.camera.decendant","aj.entity_camera.bone.camera.decendant.locator","aj.entity_camera.bone.camera.tree","aj.entity_camera.bone.root.decendant","aj.entity_camera.bone.root.decendant.locator","aj.entity_camera.bone.root.tree","aj.entity_camera.entity","aj.entity_camera.locator","aj.entity_camera.locator.ray","aj.entity_camera.node","aj.entity_camera.node.ray","aj.global.bone.camera.child","aj.global.bone.camera.child.locator","aj.global.bone.camera.decendant","aj.global.bone.camera.decendant.locator","aj.global.bone.camera.tree","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.ray","aj.new","entity.kill_when_reset"]}
execute as @n[ type=minecraft:item_display, tag=aj.entity_camera.locator.ray, tag=aj.new, distance=..2 ] run function aj:entity_camera/zzz/summon/as_locator/ray
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.ray set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.ray.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_camera.node.bone] run function aj:entity_camera/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_camera.node.camera] run function aj:entity_camera/zzz/summon/as_node/camera
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.camera set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_camera.node.root] run function aj:entity_camera/zzz/summon/as_node/root
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.root set from storage animated_java:gu out
function aj:entity_camera/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.ray
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function aj:entity_camera/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:entity_camera/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:entity_camera/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:entity_camera/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount