# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.2757f,-0.0161f,0f,-0.0282f,-0.0161f,0.2757f,0f,0.4824f,0f,0f,-0.2761f,0.0345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.2757f,-0.0161f,0f,-0.0251f,-0.0161f,0.2757f,0f,0.4307f,0f,0f,-0.2761f,0.0345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.2757f,-0.0161f,0f,-0.0251f,-0.0161f,0.2757f,0f,0.4307f,0f,0f,-0.2761f,-0.0014f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.2757f,-0.0161f,0f,-0.0171f,-0.0161f,0.2757f,0f,0.2929f,0f,0f,-0.2761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.2757f,-0.0161f,0f,-0.0101f,-0.0161f,0.2757f,0f,0.1723f,0f,0f,-0.2761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.2757f,-0.0161f,0f,0f,-0.0161f,0.2757f,0f,0f,0f,0f,-0.2761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0271473441,"py":0.4651694498,"pz":0.172578125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args