# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.034f,-0.0013f,0f,-0.0023f,-0.0013f,0.034f,0f,0.0595f,0f,0f,-0.034f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.034f,-0.0013f,0f,-0.002f,-0.0013f,0.034f,0f,0.0531f,0f,0f,-0.034f,0.0043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.034f,-0.0013f,0f,-0.002f,-0.0013f,0.034f,0f,0.0531f,0f,0f,-0.034f,-0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.034f,-0.0013f,0f,-0.0014f,-0.0013f,0.034f,0f,0.0361f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.034f,-0.0013f,0f,-0.0008f,-0.0013f,0.034f,0f,0.0212f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.034f,-0.0013f,0f,0f,-0.0013f,0.034f,0f,0f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0021817874,"py":0.0573335018,"pz":0.02125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args