# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.1368f,-0.0178f,0f,-0.0312f,-0.0178f,0.1368f,0f,0.2395f,0f,0f,-0.138f,0.0173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.1368f,-0.0178f,0f,-0.0278f,-0.0178f,0.1368f,0f,0.2138f,0f,0f,-0.138f,0.0173f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.1368f,-0.0178f,0f,-0.0278f,-0.0178f,0.1368f,0f,0.2138f,0f,0f,-0.138f,-0.0007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.1368f,-0.0178f,0f,-0.0189f,-0.0178f,0.1368f,0f,0.1454f,0f,0f,-0.138f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.1368f,-0.0178f,0f,-0.0111f,-0.0178f,0.1368f,0f,0.0855f,0f,0f,-0.138f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.1368f,-0.0178f,0f,0f,-0.0178f,0.1368f,0f,0f,0f,0f,-0.138f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.030043803,"py":0.2309288538,"pz":0.08625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args