# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.2226f,-0.0237f,0f,-0.0415f,-0.0237f,0.2226f,0f,0.3896f,0f,0f,-0.2239f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.2226f,-0.0237f,0f,-0.0371f,-0.0237f,0.2226f,0f,0.3478f,0f,0f,-0.2239f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.2226f,-0.0237f,0f,-0.0371f,-0.0237f,0.2226f,0f,0.3478f,0f,0f,-0.2239f,-0.0012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.2226f,-0.0237f,0f,-0.0252f,-0.0237f,0.2226f,0f,0.2365f,0f,0f,-0.2239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.2226f,-0.0237f,0f,-0.0148f,-0.0237f,0.2226f,0f,0.1391f,0f,0f,-0.2239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.2226f,-0.0237f,0f,0f,-0.0237f,0.2226f,0f,0f,0f,0f,-0.2239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0400142749,"py":0.3756639902,"pz":0.139921875,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args