# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entity_camera rig_hash set value 'b4a78b3462edf387705848db62e9240b843ec5580e26dea12703d9fe45d0dc4e'
scoreboard objectives add aj.grow.frame dummy
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.vanish.frame dummy