# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(head) {transformation: [-0.9995f,0.0108f,0.0291f,0f,0.0145f,0.9914f,0.1304f,1.4025f,-0.0274f,0.1307f,-0.991f,-11.9752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_arm) {transformation: [-0.9814f,0.0991f,-0.1647f,-0.247f,0.1213f,0.984f,-0.1308f,-1022.6193f,0.1491f,-0.1483f,-0.9776f,-12.0407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_arm) {transformation: [-0.9922f,-0.1022f,0.0712f,0.2484f,-0.0675f,0.9216f,0.3823f,-2046.6288f,-0.1047f,0.3745f,-0.9213f,-11.9495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(torso) {transformation: [-0.9981f,0f,0.0618f,0f,0.0187f,0.9533f,0.3015f,-3070.5975f,-0.0589f,0.3021f,-0.9514f,-11.9752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(right_leg) {transformation: [-0.9848f,-0.0596f,0.1631f,-0.125f,0.0522f,0.7941f,0.6056f,-4095.272f,-0.1656f,0.6049f,-0.7789f,-12.2203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(left_leg) {transformation: [-0.9983f,0.0385f,-0.0435f,0.125f,0.0219f,0.9429f,0.3322f,-5119.308f,0.0538f,0.3307f,-0.9422f,-12.1208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(door) {transformation: [-2f,0f,0f,0f,0f,2f,0f,2.8816f,0f,0f,-2f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":6.659016970363734e-16,"py":2.0625,"pz":-5.4375,"ry":180.00000000000003,"rx":2.5000000000000044}},"locators":{}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args