# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.7498f,0.5249f,-0.4028f,0.0252f,0f,0.6088f,0.7934f,0.5129f,0.6617f,0.5949f,-0.4565f,-0.284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.7498f,0.5249f,-0.4028f,0.0984f,0f,0.6088f,0.7934f,0.6766f,0.6617f,0.5949f,-0.4565f,-0.201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7498f,0.5249f,-0.4028f,0f,0f,0.6088f,0.7934f,0.5625f,0.6617f,0.5949f,-0.4565f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.1411401696 ^0.4898414273 ^-0.1525580282 rotated ~318.5733333333 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/104_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.1411401696,"py":0.4898414273,"pz":-0.1525580282,"ry":318.5733333333,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args