# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9868f,0.1285f,-0.0986f,0.0062f,0f,0.6088f,0.7934f,0.5129f,0.162f,0.7829f,-0.6007f,-0.275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9868f,0.1285f,-0.0986f,0.0241f,0f,0.6088f,0.7934f,0.6766f,0.162f,0.7829f,-0.6007f,-0.1657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9868f,0.1285f,-0.0986f,0f,0f,0.6088f,0.7934f,0.5625f,0.162f,0.7829f,-0.6007f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0345562183 ^0.4898414273 ^-0.1020057018 rotated ~350.6770833333 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/125_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0345562183,"py":0.4898414273,"pz":-0.1020057018,"ry":350.6770833333,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args