# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9286f,-0.2944f,0.2259f,-0.0141f,0f,0.6088f,0.7934f,0.5129f,-0.371f,0.7367f,-0.5653f,-0.2772f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9286f,-0.2944f,0.2259f,-0.0552f,0f,0.6088f,0.7934f,0.6766f,-0.371f,0.7367f,-0.5653f,-0.1744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9286f,-0.2944f,0.2259f,0f,0f,0.6088f,0.7934f,0.5625f,-0.371f,0.7367f,-0.5653f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.079148052 ^0.4898414273 ^-0.1144152513 rotated ~21.78 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/142_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.079148052,"py":0.4898414273,"pz":-0.1144152513,"ry":21.78,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args