# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9173f,-0.3158f,0.2423f,-0.0151f,0f,0.6088f,0.7934f,0.5129f,-0.3981f,0.7278f,-0.5584f,-0.2776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9173f,-0.3158f,0.2423f,-0.0592f,0f,0.6088f,0.7934f,0.6766f,-0.3981f,0.7278f,-0.5584f,-0.176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9173f,-0.3158f,0.2423f,0f,0f,0.6088f,0.7934f,0.5625f,-0.3981f,0.7278f,-0.5584f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0849199235 ^0.4898414273 ^-0.1168201891 rotated ~23.4595833333 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/143_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0849199235,"py":0.4898414273,"pz":-0.1168201891,"ry":23.4595833333,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args