# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.8675f,-0.3946f,0.3028f,-0.0189f,0f,0.6088f,0.7934f,0.5129f,-0.4974f,0.6883f,-0.5281f,-0.2795f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.8675f,-0.3946f,0.3028f,-0.074f,0f,0.6088f,0.7934f,0.6766f,-0.4974f,0.6883f,-0.5281f,-0.1835f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8675f,-0.3946f,0.3028f,0f,0f,0.6088f,0.7934f,0.5625f,-0.4974f,0.6883f,-0.5281f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.1061006549 ^0.4898414273 ^-0.1274469459 rotated ~29.8279166667 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/147_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.1061006549,"py":0.4898414273,"pz":-0.1274469459,"ry":29.8279166667,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args