# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.8543f,-0.4124f,0.3164f,-0.0198f,0f,0.6088f,0.7934f,0.5129f,-0.5198f,0.6777f,-0.5201f,-0.28f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.8543f,-0.4124f,0.3164f,-0.0773f,0f,0.6088f,0.7934f,0.6766f,-0.5198f,0.6777f,-0.5201f,-0.1854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8543f,-0.4124f,0.3164f,0f,0f,0.6088f,0.7934f,0.5625f,-0.5198f,0.6777f,-0.5201f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.1108832434 ^0.4898414273 ^-0.1302724276 rotated ~31.32 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/148_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.1108832434,"py":0.4898414273,"pz":-0.1302724276,"ry":31.32,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args