# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.7874f,-0.489f,0.3753f,-0.0235f,0f,0.6088f,0.7934f,0.5129f,-0.6164f,0.6247f,-0.4793f,-0.2825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.7874f,-0.489f,0.3753f,-0.0917f,0f,0.6088f,0.7934f,0.6766f,-0.6164f,0.6247f,-0.4793f,-0.1954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7874f,-0.489f,0.3753f,0f,0f,0.6088f,0.7934f,0.5625f,-0.6164f,0.6247f,-0.4793f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.1314904587 ^0.4898414273 ^-0.1445350004 rotated ~38.0554166667 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/153_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.1314904587,"py":0.4898414273,"pz":-0.1445350004,"ry":38.0554166667,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args