# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.7745f,-0.5019f,0.3851f,-0.0241f,0f,0.6088f,0.7934f,0.5129f,-0.6326f,0.6145f,-0.4715f,-0.283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.7745f,-0.5019f,0.3851f,-0.0941f,0f,0.6088f,0.7934f,0.6766f,-0.6326f,0.6145f,-0.4715f,-0.1973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7745f,-0.5019f,0.3851f,0f,0f,0.6088f,0.7934f,0.5625f,-0.6326f,0.6145f,-0.4715f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.1349347656 ^0.4898414273 ^-0.1472892532 rotated ~39.24 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/154_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.1349347656,"py":0.4898414273,"pz":-0.1472892532,"ry":39.24,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args