# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.8932f,-0.3567f,0.2737f,-0.0171f,0f,0.6088f,0.7934f,0.5129f,-0.4496f,0.7086f,-0.5438f,-0.2785f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.8932f,-0.3567f,0.2737f,-0.0669f,0f,0.6088f,0.7934f,0.6766f,-0.4496f,0.7086f,-0.5438f,-0.1796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8932f,-0.3567f,0.2737f,0f,0f,0.6088f,0.7934f,0.5625f,-0.4496f,0.7086f,-0.5438f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0959074629 ^0.4898414273 ^-0.1219645955 rotated ~26.71875 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/35_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0959074629,"py":0.4898414273,"pz":-0.1219645955,"ry":26.71875,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args