# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9393f,-0.2723f,0.2089f,-0.0131f,0f,0.6088f,0.7934f,0.5129f,-0.3432f,0.7452f,-0.5718f,-0.2768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9393f,-0.2723f,0.2089f,-0.051f,0f,0.6088f,0.7934f,0.6766f,-0.3432f,0.7452f,-0.5718f,-0.1728f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9393f,-0.2723f,0.2089f,0f,0f,0.6088f,0.7934f,0.5625f,-0.3432f,0.7452f,-0.5718f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0732032743 ^0.4898414273 ^-0.112142164 rotated ~20.0704166667 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/39_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0732032743,"py":0.4898414273,"pz":-0.112142164,"ry":20.0704166667,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args