# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9585f,-0.2263f,0.1736f,-0.0109f,0f,0.6088f,0.7934f,0.5129f,-0.2852f,0.7604f,-0.5835f,-0.276f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9585f,-0.2263f,0.1736f,-0.0424f,0f,0.6088f,0.7934f,0.6766f,-0.2852f,0.7604f,-0.5835f,-0.1699f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9585f,-0.2263f,0.1736f,0f,0f,0.6088f,0.7934f,0.5625f,-0.2852f,0.7604f,-0.5835f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0608381558 ^0.4898414273 ^-0.1080478036 rotated ~16.57125 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/41_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0608381558,"py":0.4898414273,"pz":-0.1080478036,"ry":16.57125,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args