# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9811f,-0.1536f,0.1178f,-0.0074f,0f,0.6088f,0.7934f,0.5129f,-0.1935f,0.7784f,-0.5973f,-0.2752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9811f,-0.1536f,0.1178f,-0.0288f,0f,0.6088f,0.7934f,0.6766f,-0.1935f,0.7784f,-0.5973f,-0.1666f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9811f,-0.1536f,0.1178f,0f,0f,0.6088f,0.7934f,0.5625f,-0.1935f,0.7784f,-0.5973f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0412864116 ^0.4898414273 ^-0.1032216828 rotated ~11.16 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/44_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0412864116,"py":0.4898414273,"pz":-0.1032216828,"ry":11.16,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args