# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9492f,0.2495f,-0.1915f,0.012f,0f,0.6088f,0.7934f,0.5129f,0.3145f,0.7531f,-0.5779f,-0.2764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9492f,0.2495f,-0.1915f,0.0468f,0f,0.6088f,0.7934f,0.6766f,0.3145f,0.7531f,-0.5779f,-0.1713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9492f,0.2495f,-0.1915f,0f,0f,0.6088f,0.7934f,0.5625f,0.3145f,0.7531f,-0.5779f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0670961507 ^0.4898414273 ^-0.1100152145 rotated ~341.6666666667 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/60_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0670961507,"py":0.4898414273,"pz":-0.1100152145,"ry":341.6666666667,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args