# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.7271f,0.5446f,-0.4179f,0.0261f,0f,0.6088f,0.7934f,0.5129f,0.6865f,0.5769f,-0.4427f,-0.2848f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.7271f,0.5446f,-0.4179f,0.1021f,0f,0.6088f,0.7934f,0.6766f,0.6865f,0.5769f,-0.4427f,-0.2043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7271f,0.5446f,-0.4179f,0f,0f,0.6088f,0.7934f,0.5625f,0.6865f,0.5769f,-0.4427f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.1464376832 ^0.4898414273 ^-0.1573936276 rotated ~316.6466666667 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/78_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.1464376832,"py":0.4898414273,"pz":-0.1573936276,"ry":316.6466666667,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args