# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.5572f,-0.6588f,0.5055f,-0.0316f,0f,0.6088f,0.7934f,0.5129f,-0.8304f,0.4421f,-0.3392f,-0.2913f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.5572f,-0.6588f,0.5055f,-0.1235f,0f,0.6088f,0.7934f,0.6766f,-0.8304f,0.4421f,-0.3392f,-0.2296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5572f,-0.6588f,0.5055f,0f,0f,0.6088f,0.7934f,0.5625f,-0.8304f,0.4421f,-0.3392f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.1771293572 ^0.4898414273 ^-0.1936422167 rotated ~56.1375 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/9_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.1771293572,"py":0.4898414273,"pz":-0.1936422167,"ry":56.1375,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args