# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.6554f,0.5992f,-0.4598f,0.0287f,0f,0.6088f,0.7934f,0.5129f,0.7553f,0.52f,-0.399f,-0.2876f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.6554f,0.5992f,-0.4598f,0.1124f,0f,0.6088f,0.7934f,0.6766f,0.7553f,0.52f,-0.399f,-0.215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6554f,0.5992f,-0.4598f,0f,0f,0.6088f,0.7934f,0.5625f,0.7553f,0.52f,-0.399f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.1611106252 ^0.4898414273 ^-0.172695321 rotated ~310.95 ~52.5 run function aj:entity_camera/animations/idle/zzz/frames/98_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.1611106252,"py":0.4898414273,"pz":-0.172695321,"ry":310.95,"rx":52.5}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args