# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(small) start_interpolation set value -1
$data modify entity $(medium) start_interpolation set value -1
$data modify entity $(final) start_interpolation set value -1