# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(petal4) interpolation_duration set value 1
$data modify entity $(petal3) interpolation_duration set value 1
$data modify entity $(petal2) interpolation_duration set value 1
$data modify entity $(petal1) interpolation_duration set value 1
$data modify entity $(root) interpolation_duration set value 1