# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify entity $(petal4) start_interpolation set value -1
$data modify entity $(petal3) start_interpolation set value -1
$data modify entity $(petal2) start_interpolation set value -1
$data modify entity $(petal1) start_interpolation set value -1
$data modify entity $(root) start_interpolation set value -1