# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.6667f,-0.0015f,0f,0f,-0.0015f,0.6667f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.6667f,0f,0f,0f,0f,0.6667f,-0.002f,0f,0f,-0.002f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.6667f,0.0007f,0f,0f,0.0007f,0.6667f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.6667f,0f,0f,0f,0f,0.6667f,0.001f,0f,0f,0.001f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}