# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.661f,-0.087f,0f,0f,-0.087f,0.661f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.6667f,0f,0f,0f,0f,0.6613f,-0.0843f,0f,0f,-0.0843f,-0.6613f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.6633f,0.0665f,0f,0f,0.0665f,0.6633f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.6667f,0f,0f,0f,0f,0.662f,0.079f,0f,0f,0.079f,-0.662f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}