# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.6614f,-0.0837f,0f,0f,-0.0837f,0.6614f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.6667f,0f,0f,0f,0f,0.6622f,-0.0771f,0f,0f,-0.0771f,-0.6622f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.6622f,0.0771f,0f,0f,0.0771f,0.6622f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.6667f,0f,0f,0f,0f,0.6611f,0.086f,0f,0f,0.086f,-0.6611f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}