# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.665f,-0.0474f,0f,0f,-0.0474f,0.665f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.6667f,0f,0f,0f,0f,0.6655f,-0.0402f,0f,0f,-0.0402f,-0.6655f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.6619f,0.0795f,0f,0f,0.0795f,0.6619f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.6667f,0f,0f,0f,0f,0.6638f,0.0617f,0f,0f,0.0617f,-0.6638f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}