# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-0.666f,-0.0288f,0f,0f,-0.0288f,0.666f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-0.6667f,0f,0f,0f,0f,0.6656f,-0.0377f,0f,0f,-0.0377f,-0.6656f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-0.6665f,0.0149f,0f,0f,0.0149f,0.6665f,0f,0f,0f,0f,-0.6667f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-0.6667f,0f,0f,0f,0f,0.6664f,0.0202f,0f,0f,0.0202f,-0.6664f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}