# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9946f,0.0019f,0.0025f,-0.0002f,0.0031f,0.6054f,0.789f,0.5132f,0f,0.789f,-0.6054f,-0.2747f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9946f,0.0019f,0.0025f,0.0004f,0.0031f,0.6054f,0.789f,0.676f,0f,0.789f,-0.6054f,-0.1646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9946f,0.0019f,0.0025f,0f,0.0031f,0.6054f,0.789f,0.5625f,0f,0.789f,-0.6054f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0002262613 ^0.4902374116 ^-0.10034956 rotated ~0.2337945389 ~52.4996339835 run function aj:entity_camera/animations/vanish/zzz/frames/1_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0002262613,"py":0.4902374116,"pz":-0.10034956,"ry":0.2337945389,"rx":52.4996339835}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args