# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9143f,0.0433f,0.0564f,-0.0035f,0.0711f,0.5566f,0.7253f,0.5172f,0f,0.7275f,-0.5583f,-0.2776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9143f,0.0433f,0.0564f,0.0081f,0.0711f,0.5566f,0.7253f,0.6669f,0f,0.7275f,-0.5583f,-0.1761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9143f,0.0433f,0.0564f,0f,0.0711f,0.5566f,0.7253f,0.5625f,0f,0.7275f,-0.5583f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0051633252 ^0.4960702936 ^-0.1168866261 rotated ~5.7667538625 ~52.2760348732 run function aj:entity_camera/animations/vanish/zzz/frames/12_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0051633252,"py":0.4960702936,"pz":-0.1168866261,"ry":5.7667538625,"rx":52.2760348732}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args