# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9037f,0.0456f,0.0594f,-0.0037f,0.0749f,0.5501f,0.7169f,0.5177f,0f,0.7194f,-0.552f,-0.278f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9037f,0.0456f,0.0594f,0.0086f,0.0749f,0.5501f,0.7169f,0.6656f,0f,0.7194f,-0.552f,-0.1776f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9037f,0.0456f,0.0594f,0f,0.0749f,0.5501f,0.7169f,0.5625f,0f,0.7194f,-0.552f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0054438889 ^0.4968402032 ^-0.1190737441 rotated ~6.1460212268 ~52.2454076563 run function aj:entity_camera/animations/vanish/zzz/frames/13_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0054438889,"py":0.4968402032,"pz":-0.1190737441,"ry":6.1460212268,"rx":52.2454076563}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args