# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.8803f,0.048f,0.0626f,-0.0039f,0.0789f,0.5359f,0.6984f,0.5189f,0f,0.7012f,-0.538f,-0.2789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.8803f,0.048f,0.0626f,0.009f,0.0789f,0.5359f,0.6984f,0.663f,0f,0.7012f,-0.538f,-0.181f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8803f,0.048f,0.0626f,0f,0.0789f,0.5359f,0.6984f,0.5625f,0f,0.7012f,-0.538f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0057324661 ^0.4985403988 ^-0.1239739402 rotated ~6.6357904956 ~52.2028924191 run function aj:entity_camera/animations/vanish/zzz/frames/15_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0057324661,"py":0.4985403988,"pz":-0.1239739402,"ry":6.6357904956,"rx":52.2028924191}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args