# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.989f,0.0045f,0.0059f,-0.0004f,0.0075f,0.6021f,0.7846f,0.5135f,0f,0.7847f,-0.6021f,-0.2749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.989f,0.0045f,0.0059f,0.0009f,0.0075f,0.6021f,0.7846f,0.6754f,0f,0.7847f,-0.6021f,-0.1654f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.989f,0.0045f,0.0059f,0f,0.0075f,0.6021f,0.7846f,0.5625f,0f,0.7847f,-0.6021f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0005419517 ^0.4906392098 ^-0.1015242045 rotated ~0.5630986065 ~52.4978766558 run function aj:entity_camera/animations/vanish/zzz/frames/2_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0005419517,"py":0.4906392098,"pz":-0.1015242045,"ry":0.5630986065,"rx":52.4978766558}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args