# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.6669f,-0.01f,-0.013f,0.0008f,-0.0164f,0.406f,0.5291f,0.5294f,0f,0.5293f,-0.4061f,-0.2871f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.6669f,-0.01f,-0.013f,-0.0019f,-0.0164f,0.406f,0.5291f,0.6386f,0f,0.5293f,-0.4061f,-0.2133f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6669f,-0.01f,-0.013f,0f,-0.0164f,0.406f,0.5291f,0.5625f,0f,0.5293f,-0.4061f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0011895841 ^0.5140417166 ^-0.1701927125 rotated ~358.1681477389 ~52.4775167471 run function aj:entity_camera/animations/vanish/zzz/frames/26_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0011895841,"py":0.5140417166,"pz":-0.1701927125,"ry":358.1681477389,"rx":52.4775167471}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args