# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.6333f,-0.0167f,-0.0217f,0.0014f,-0.0274f,0.3855f,0.5025f,0.5311f,0f,0.5029f,-0.3859f,-0.2884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.6333f,-0.0167f,-0.0217f,-0.0031f,-0.0274f,0.3855f,0.5025f,0.6348f,0f,0.5029f,-0.3859f,-0.2182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6333f,-0.0167f,-0.0217f,0f,-0.0274f,0.3855f,0.5025f,0.5625f,0f,0.5029f,-0.3859f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0019877792 ^0.5164830549 ^-0.1772769004 rotated ~356.7809300727 ~52.4304875606 run function aj:entity_camera/animations/vanish/zzz/frames/27_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0019877792,"py":0.5164830549,"pz":-0.1772769004,"ry":356.7809300727,"rx":52.4304875606}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args