# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.3974f,-0.0307f,-0.04f,0.0025f,-0.0505f,0.242f,0.3153f,0.5428f,0f,0.3178f,-0.2439f,-0.2973f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.3974f,-0.0307f,-0.04f,-0.0058f,-0.0505f,0.242f,0.3153f,0.6079f,0f,0.3178f,-0.2439f,-0.2529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.3974f,-0.0307f,-0.04f,0f,-0.0505f,0.242f,0.3153f,0.5625f,0f,0.3178f,-0.2439f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.003666586 ^0.5336220091 ^-0.2270390011 rotated ~350.6780142023 ~51.9092697932 run function aj:entity_camera/animations/vanish/zzz/frames/33_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.003666586,"py":0.5336220091,"pz":-0.2270390011,"ry":350.6780142023,"rx":51.9092697932}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args