# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.2369f,-0.0169f,-0.0221f,0.0014f,-0.0278f,0.1442f,0.188f,0.5508f,0f,0.1892f,-0.1452f,-0.3034f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.2369f,-0.0169f,-0.0221f,-0.0032f,-0.0278f,0.1442f,0.188f,0.5895f,0f,0.1892f,-0.1452f,-0.277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.2369f,-0.0169f,-0.0221f,0f,-0.0278f,0.1442f,0.188f,0.5625f,0f,0.1892f,-0.1452f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0020204171 ^0.5452860094 ^-0.2616160484 rotated ~351.3618133352 ~51.993843372 run function aj:entity_camera/animations/vanish/zzz/frames/37_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0020204171,"py":0.5452860094,"pz":-0.2616160484,"ry":351.3618133352,"rx":51.993843372}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args