# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.9774f,0.0115f,0.015f,-0.0009f,0.019f,0.595f,0.7754f,0.514f,0f,0.7756f,-0.5951f,-0.2753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.9774f,0.0115f,0.015f,0.0022f,0.019f,0.595f,0.7754f,0.6741f,0f,0.7756f,-0.5951f,-0.1671f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9774f,0.0115f,0.015f,0f,0.019f,0.595f,0.7754f,0.5625f,0f,0.7756f,-0.5951f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^-0.0013773908 ^0.4914820917 ^-0.1039655366 rotated ~1.4476293159 ~52.4859622034 run function aj:entity_camera/animations/vanish/zzz/frames/4_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":-0.0013773908,"py":0.4914820917,"pz":-0.1039655366,"ry":1.4476293159,"rx":52.4859622034}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args