# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) {transformation: [-0.1292f,-0.0055f,-0.0072f,0.0005f,-0.0091f,0.0787f,0.1025f,0.5561f,0f,0.1028f,-0.0789f,-0.3076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(camera) {transformation: [-0.1292f,-0.0055f,-0.0072f,-0.001f,-0.0091f,0.0787f,0.1025f,0.5772f,0f,0.1028f,-0.0789f,-0.2932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.1292f,-0.0055f,-0.0072f,0f,-0.0091f,0.0787f,0.1025f,0.5625f,0f,0.1028f,-0.0789f,-0.3125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(ray) positioned ^0.0006613172 ^0.5531108436 ^-0.2848669092 rotated ~354.7683163131 ~52.3158555552 run function aj:entity_camera/animations/vanish/zzz/frames/40_locator_ray
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"ray":{"px":0.0006613172,"py":0.5531108436,"pz":-0.2848669092,"ry":354.7683163131,"rx":52.3158555552}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args