# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
function animated_java:global/remove/entity_stack_by_uuid with storage animated_java:temp entry.data.locators.entity_hitbox
execute unless data storage animated_java:temp {entry:{data:{rig_hash: 'e30df68744361bd3e967bfecf10224764469f60e1ddf333677bb2fddb0a577a2'}}} run function animated_java:global/remove/outdated_rig
function aj:entity_trap/remove/this/zzz/0 with storage animated_java:temp entry.data.uuids_by_name
function animated_java:global/remove/entity_stack