# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone) { transformation: [-1f,0f,0f,0f,0f,0.6088f,0.7934f,0.5129f,0f,0.7934f,-0.6088f,-0.2745f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(camera) { transformation: [-1f,0f,0f,0f,0f,0.6088f,0.7934f,0.6766f,0f,0.7934f,-0.6088f,-0.1637f,0f,0f,0f,1f], start_interpolation: 0 }
$data merge entity $(root) { transformation: [-1f,0f,0f,0f,0f,0.6088f,0.7934f,0.5625f,0f,0.7934f,-0.6088f,-0.3125f,0f,0f,0f,1f], start_interpolation: 0 }