# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entity_trap rig_hash set value 'e30df68744361bd3e967bfecf10224764469f60e1ddf333677bb2fddb0a577a2'
scoreboard objectives add aj.medium_grow.frame dummy
scoreboard objectives add aj.medium_idle.frame dummy
scoreboard objectives add aj.large_grow.frame dummy
scoreboard objectives add aj.large_idle.frame dummy
scoreboard objectives add aj.capture.frame dummy
scoreboard objectives add aj.release.frame dummy