# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entity_trap rig_hash set value '303fad0ff1c7949dd9063a9b61142e0d1c7329f6ee0772fba295adfa65331bec'
scoreboard objectives add aj.medium_grow.frame dummy
scoreboard objectives add aj.medium_idle.frame dummy
scoreboard objectives add aj.large_grow.frame dummy
scoreboard objectives add aj.large_idle.frame dummy
scoreboard objectives add aj.capture.frame dummy
scoreboard objectives add aj.release.frame dummy