# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.8617f,0.0231f,0f,0.0608f,0.0231f,0.8617f,0f,2.2619f,0f,0f,-0.862f,0.1616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.8617f,0.0231f,0f,0.0543f,0.0231f,0.8617f,0f,2.0196f,0f,0f,-0.862f,0.1616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.8617f,0.0231f,0f,0.0543f,0.0231f,0.8617f,0f,2.0196f,0f,0f,-0.862f,-0.0067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.8617f,0.0231f,0f,0.0369f,0.0231f,0.8617f,0f,1.3733f,0f,0f,-0.862f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.8617f,0.0231f,0f,0.0217f,0.0231f,0.8617f,0f,0.8078f,0f,0f,-0.862f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8617f,0.0231f,0f,0f,0.0231f,0.8617f,0f,0f,0f,0f,-0.862f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0585916235,"py":2.1811506769,"pz":0.808125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args