# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9156f,0.0667f,0f,0.1751f,0.0667f,0.9156f,0f,2.4034f,0f,0f,-0.918f,0.1721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9156f,0.0667f,0f,0.1563f,0.0667f,0.9156f,0f,2.1459f,0f,0f,-0.918f,0.1721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9156f,0.0667f,0f,0.1563f,0.0667f,0.9156f,0f,2.1459f,0f,0f,-0.918f,-0.0072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9156f,0.0667f,0f,0.1063f,0.0667f,0.9156f,0f,1.4592f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9156f,0.0667f,0f,0.0625f,0.0667f,0.9156f,0f,0.8584f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9156f,0.0667f,0f,0f,0.0667f,0.9156f,0f,0f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.1688175647,"py":2.3175470281,"pz":0.860625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args