# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9398f,0.0822f,0f,0.2158f,0.0822f,0.9398f,0f,2.4669f,0f,0f,-0.9434f,0.1769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9398f,0.0822f,0f,0.1927f,0.0822f,0.9398f,0f,2.2026f,0f,0f,-0.9434f,0.1769f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9398f,0.0822f,0f,0.1927f,0.0822f,0.9398f,0f,2.2026f,0f,0f,-0.9434f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9398f,0.0822f,0f,0.131f,0.0822f,0.9398f,0f,1.4978f,0f,0f,-0.9434f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9398f,0.0822f,0f,0.0771f,0.0822f,0.9398f,0f,0.881f,0f,0f,-0.9434f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9398f,0.0822f,0f,0f,0.0822f,0.9398f,0f,0f,0f,0f,-0.9434f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.2081207642,"py":2.3788312199,"pz":0.8844140625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args