# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9962f,0.0872f,0f,0.2288f,0.0872f,0.9962f,0f,2.615f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9962f,0.0872f,0f,0.2043f,0.0872f,0.9962f,0f,2.3348f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9962f,0.0872f,0f,0.2043f,0.0872f,0.9962f,0f,2.3348f,0f,0f,-1f,-0.0078f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9962f,0.0872f,0f,0.1389f,0.0872f,0.9962f,0f,1.5877f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9962f,0.0872f,0f,0.0817f,0.0872f,0.9962f,0f,0.9339f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9962f,0.0872f,0f,0f,0.0872f,0.9962f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$execute unless entity @s[tag=aj.transforms_only] as $(entity_hitbox) positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:entity_crown_piranha/animations/large_grow/zzz/frames/20_locator_entity_hitbox
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.2206129738,"py":2.5216178295,"pz":0.9375,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute unless entity @s[tag=aj.transforms_only] at @s run function aj:entity_crown_piranha/animations/large_grow/zzz/frames/20_root_function