# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.6053f,-0.07f,0f,-0.1837f,-0.07f,0.6053f,0f,1.589f,0f,0f,-0.6094f,0.1143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.6053f,-0.07f,0f,-0.1641f,-0.07f,0.6053f,0f,1.4188f,0f,0f,-0.6094f,0.1143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.6053f,-0.07f,0f,-0.1641f,-0.07f,0.6053f,0f,1.4188f,0f,0f,-0.6094f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6053f,-0.07f,0f,-0.1116f,-0.07f,0.6053f,0f,0.9648f,0f,0f,-0.6094f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.6053f,-0.07f,0f,-0.0656f,-0.07f,0.6053f,0f,0.5675f,0f,0f,-0.6094f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6053f,-0.07f,0f,0f,-0.07f,0.6053f,0f,0f,0f,0f,-0.6094f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.1771869513,"py":1.5322698133,"pz":0.5712890625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args