# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.7198f,-0.0767f,0f,-0.2013f,-0.0767f,0.7198f,0f,1.8895f,0f,0f,-0.7239f,0.1357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7198f,-0.0767f,0f,-0.1797f,-0.0767f,0.7198f,0f,1.687f,0f,0f,-0.7239f,0.1357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.7198f,-0.0767f,0f,-0.1797f,-0.0767f,0.7198f,0f,1.687f,0f,0f,-0.7239f,-0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.7198f,-0.0767f,0f,-0.1222f,-0.0767f,0.7198f,0f,1.1472f,0f,0f,-0.7239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7198f,-0.0767f,0f,-0.0719f,-0.0767f,0.7198f,0f,0.6748f,0f,0f,-0.7239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7198f,-0.0767f,0f,0f,-0.0767f,0.7198f,0f,0f,0f,0f,-0.7239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.1940725843,"py":1.8220018152,"pz":0.6786328125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args