# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute at @s run function aj:entity_crown_piranha/zzz/set_default_pose/as_locator_entity_hitbox with storage animated_java:temp entry.data.locators.entity_hitbox
data modify storage animated_java:temp entry.data.locators.locator merge value { px: 0, py: 2.53125, pz: 0.9375, ry: 0, rx: 0 }