# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:vine_wall rig_hash set value 'cc59be906b9215e2233771c4131e5bb1076f087e7fe64993615fc7f961afa192'
scoreboard objectives add aj.open.frame dummy
scoreboard objectives add aj.reset.frame dummy
scoreboard objectives add aj.reset_noint.frame dummy
scoreboard objectives add aj.open_small.frame dummy
scoreboard objectives add aj.reset_noint_small.frame dummy