# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.open_small.frame matches 17.. run scoreboard players set @s aj.open_small.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.open_small.frame
execute at @s run function aj:vine_wall/animations/open_small/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.open_small.frame 1