# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:vine_wall/animations/pause_all
scoreboard players set @s aj.reset_noint_small.frame 0
tag @s add aj.transforms_only
execute at @s run function aj:vine_wall/animations/reset_noint_small/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only