# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:entity_piranha"
data modify storage animated_java:temp entry.data.rig_hash set value "2cdfe802ec35a4550c3a601a45597f0746515113f7e2142cb55418727a605a80"
tp @s ~ ~ ~ ~ ~
summon minecraft:interaction ^0 ^0 ^0 {Tags:["aj.entity_piranha.bone.root.child","aj.entity_piranha.bone.root.child.locator","aj.entity_piranha.bone.root.decendant","aj.entity_piranha.bone.root.decendant.locator","aj.entity_piranha.bone.root.tree","aj.entity_piranha.entity","aj.entity_piranha.locator","aj.entity_piranha.locator.entity_hitbox","aj.entity_piranha.node","aj.entity_piranha.node.entity_hitbox","aj.global.bone.root.child","aj.global.bone.root.child.locator","aj.global.bone.root.decendant","aj.global.bone.root.decendant.locator","aj.global.bone.root.tree","aj.global.entity","aj.global.locator","aj.global.node","aj.global.node.entity_hitbox","aj.new","entity.kill_when_reset"]}
execute as @n[ type=minecraft:interaction, tag=aj.entity_piranha.locator.entity_hitbox, tag=aj.new, distance=..1 ] run function aj:entity_piranha/zzz/summon/as_locator/entity_hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.entity_hitbox set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.locators.entity_hitbox.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.bone2] run function aj:entity_piranha/zzz/summon/as_node/bone2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.bone3] run function aj:entity_piranha/zzz/summon/as_node/bone3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.bone1] run function aj:entity_piranha/zzz/summon/as_node/bone1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.bone] run function aj:entity_piranha/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.bone4] run function aj:entity_piranha/zzz/summon/as_node/bone4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.root] run function aj:entity_piranha/zzz/summon/as_node/root
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.root set from storage animated_java:gu out
function aj:entity_piranha/zzz/summon/zzz/0 with storage animated_java:temp entry.data.locators.entity_hitbox
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:temp uuids
function aj:entity_piranha/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:entity_piranha/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:entity_piranha/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:entity_piranha/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
function aj:entity_piranha/zzz/summon/zzz/1 with storage animated_java:temp entry.data.locators.entity_hitbox
execute at @s run function aj:entity_piranha/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount