# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:entity_piranha"
data modify storage animated_java:temp entry.data.rig_hash set value "9837f930286de28f82d5ae46f9c3a0b6bfb9182528b98164afbd6590993f964b"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.entity_piranha.node.small] run function aj:entity_piranha/zzz/summon/as_node/small
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.small set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.medium] run function aj:entity_piranha/zzz/summon/as_node/medium
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.medium set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.entity_piranha.node.final] run function aj:entity_piranha/zzz/summon/as_node/final
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.final set from storage animated_java:gu out
function aj:entity_piranha/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:entity_piranha/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:entity_piranha/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 1
execute on passengers run data modify entity @s teleport_duration set value 1
execute at @s run function aj:entity_piranha/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new
execute on passengers run ride @s dismount