# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.3223f,-0.1711f,0f,0f,-0.1711f,1.3223f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.3221f,-0.1726f,0f,0f,-0.1726f,-1.3221f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.3279f,0.1208f,0f,0f,0.1208f,1.3279f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.3252f,0.147f,0f,0f,0.147f,-1.3252f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}