# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.3288f,-0.11f,0f,0f,-0.11f,1.3288f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.33f,-0.0941f,0f,0f,-0.0941f,-1.33f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.3225f,0.17f,0f,0f,0.17f,1.3225f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.326f,0.1397f,0f,0f,0.1397f,-1.326f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}