# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.33f,-0.0949f,0f,0f,-0.0949f,1.33f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.3309f,-0.0803f,0f,0f,-0.0803f,-1.3309f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.3238f,0.1589f,0f,0f,0.1589f,1.3238f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.3276f,0.1235f,0f,0f,0.1235f,-1.3276f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}