# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.331f,-0.0795f,0f,0f,-0.0795f,1.331f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.3317f,-0.0667f,0f,0f,-0.0667f,-1.3317f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.3257f,0.1424f,0f,0f,0.1424f,1.3257f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.3291f,0.1057f,0f,0f,0.1057f,-1.3291f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}