# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.3324f,-0.0499f,0f,0f,-0.0499f,1.3324f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.3327f,-0.0412f,0f,0f,-0.0412f,-1.3327f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.3296f,0.099f,0f,0f,0.099f,1.3296f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.3316f,0.0687f,0f,0f,0.0687f,-1.3316f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}