# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(petal4) {transformation: [-1.3333f,-0.0144f,0f,0f,-0.0144f,1.3333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal3) {transformation: [-1.3333f,0f,0f,0f,0f,1.3333f,-0.0117f,0f,0f,-0.0117f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal2) {transformation: [-1.333f,0.0319f,0f,0f,0.0319f,1.333f,0f,0f,0f,0f,-1.3333f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(petal1) {transformation: [-1.3333f,0f,0f,0f,0f,1.3332f,0.0206f,0f,0f,0.0206f,-1.3332f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}