# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.0149f,-0.0002f,0f,-0.0006f,-0.0002f,0.0149f,0f,0.039f,0f,0f,-0.0149f,0.0028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.0149f,-0.0002f,0f,-0.0005f,-0.0002f,0.0149f,0f,0.0349f,0f,0f,-0.0149f,0.0028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.0149f,-0.0002f,0f,-0.0005f,-0.0002f,0.0149f,0f,0.0349f,0f,0f,-0.0149f,-0.0001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.0149f,-0.0002f,0f,-0.0004f,-0.0002f,0.0149f,0f,0.0237f,0f,0f,-0.0149f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.0149f,-0.0002f,0f,-0.0002f,-0.0002f,0.0149f,0f,0.0139f,0f,0f,-0.0149f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.0149f,-0.0002f,0f,0f,-0.0002f,0.0149f,0f,0f,0f,0f,-0.0149f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0005603832,"py":0.0376481734,"pz":0.0139453125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args