# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.3039f,-0.0091f,0f,-0.0239f,-0.0091f,0.3039f,0f,0.7976f,0f,0f,-0.304f,0.057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.3039f,-0.0091f,0f,-0.0214f,-0.0091f,0.3039f,0f,0.7122f,0f,0f,-0.304f,0.057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.3039f,-0.0091f,0f,-0.0214f,-0.0091f,0.3039f,0f,0.7122f,0f,0f,-0.304f,-0.0024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.3039f,-0.0091f,0f,-0.0145f,-0.0091f,0.3039f,0f,0.4843f,0f,0f,-0.304f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.3039f,-0.0091f,0f,-0.0085f,-0.0091f,0.3039f,0f,0.2849f,0f,0f,-0.304f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.3039f,-0.0091f,0f,0f,-0.0091f,0.3039f,0f,0f,0f,0f,-0.304f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.023079881,"py":0.7691538007,"pz":0.285,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args