# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.034f,-0.0013f,0f,-0.0034f,-0.0013f,0.034f,0f,0.0892f,0f,0f,-0.034f,0.0064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.034f,-0.0013f,0f,-0.003f,-0.0013f,0.034f,0f,0.0796f,0f,0f,-0.034f,0.0064f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.034f,-0.0013f,0f,-0.003f,-0.0013f,0.034f,0f,0.0796f,0f,0f,-0.034f,-0.0003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.034f,-0.0013f,0f,-0.0021f,-0.0013f,0.034f,0f,0.0541f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.034f,-0.0013f,0f,-0.0012f,-0.0013f,0.034f,0f,0.0319f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.034f,-0.0013f,0f,0f,-0.0013f,0.034f,0f,0f,0f,0f,-0.034f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.003272681,"py":0.0860002527,"pz":0.031875,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args