# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.0817f,-0.0076f,0f,-0.0199f,-0.0076f,0.0817f,0f,0.2143f,0f,0f,-0.082f,0.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.0817f,-0.0076f,0f,-0.0177f,-0.0076f,0.0817f,0f,0.1914f,0f,0f,-0.082f,0.0154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.0817f,-0.0076f,0f,-0.0177f,-0.0076f,0.0817f,0f,0.1914f,0f,0f,-0.082f,-0.0006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.0817f,-0.0076f,0f,-0.0121f,-0.0076f,0.0817f,0f,0.1301f,0f,0f,-0.082f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.0817f,-0.0076f,0f,-0.0071f,-0.0076f,0.0817f,0f,0.0765f,0f,0f,-0.082f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.0817f,-0.0076f,0f,0f,-0.0076f,0.0817f,0f,0f,0f,0f,-0.082f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.019142172,"py":0.2066779346,"pz":0.076875,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args