# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-1f,-0.0079f,0f,-0.0208f,-0.0079f,1f,0.0039f,2.6242f,0f,0.0039f,-1f,0.1933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-1f,-0.0079f,0f,-0.0186f,-0.0079f,1f,0.0039f,2.3429f,0f,0.0039f,-1f,0.1922f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-1f,-0.0079f,0f,-0.0186f,-0.0079f,1f,0.0039f,2.3437f,0f,0.0039f,-1f,-0.0031f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-1f,-0.0079f,0f,-0.0127f,-0.0079f,1f,0.0039f,1.5937f,0f,0.0039f,-1f,0.0018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-1f,-0.0079f,0f,-0.0074f,-0.0079f,1f,0.0028f,0.9375f,0f,0.0028f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-1f,-0.0079f,0f,0f,-0.0079f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0200720254,"py":2.5275124538,"pz":0.9429652245,"ry":359.9982294055,"rx":0.2229559326}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args