# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9998f,-0.0181f,-0.0003f,-0.0476f,-0.0182f,0.9997f,0.0148f,2.6216f,0f,0.0148f,-0.9999f,0.2097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9998f,-0.0181f,-0.0003f,-0.0425f,-0.0182f,0.9997f,0.0148f,2.3405f,0f,0.0148f,-0.9999f,0.2056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9998f,-0.0181f,-0.0003f,-0.0425f,-0.0182f,0.9997f,0.0148f,2.3434f,0f,0.0148f,-0.9999f,0.0103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9998f,-0.0181f,-0.0003f,-0.0289f,-0.0182f,0.9997f,0.0148f,1.5935f,0f,0.0148f,-0.9999f,0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9998f,-0.0181f,-0.0002f,-0.017f,-0.0182f,0.9998f,0.0106f,0.9373f,0f,0.0106f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9998f,-0.0182f,0f,0f,-0.0182f,0.9998f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0456881876,"py":2.516781564,"pz":0.9582673345,"ry":359.9845642812,"rx":0.8502302764}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args