# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9996f,0.0289f,0.0016f,0.0757f,0.029f,0.9981f,0.0535f,2.6119f,0f,0.0535f,-0.9986f,0.2676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9996f,0.0289f,0.0016f,0.0676f,0.029f,0.9981f,0.0535f,2.3312f,0f,0.0535f,-0.9986f,0.2525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9996f,0.0289f,0.0016f,0.0679f,0.029f,0.9981f,0.0535f,2.3416f,0f,0.0535f,-0.9986f,0.0575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9996f,0.0289f,0.0016f,0.0462f,0.029f,0.9981f,0.0535f,1.5926f,0f,0.0535f,-0.9986f,0.0251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9996f,0.0289f,0.0011f,0.0272f,0.029f,0.9988f,0.0382f,0.9371f,0f,0.0383f,-0.9993f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9996f,0.029f,0f,0f,0.029f,0.9996f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0718191179,"py":2.4781812764,"pz":1.0114647634,"ry":0.0890074013,"rx":3.0683401572}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args