# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9997f,0.0254f,0.0011f,0.0666f,0.0254f,0.9988f,0.0421f,2.615f,0f,0.0421f,-0.9991f,0.2505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9997f,0.0254f,0.0011f,0.0594f,0.0254f,0.9988f,0.0421f,2.3341f,0f,0.0421f,-0.9991f,0.2387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9997f,0.0254f,0.0011f,0.0596f,0.0254f,0.9988f,0.0421f,2.3424f,0f,0.0421f,-0.9991f,0.0435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9997f,0.0254f,0.0011f,0.0405f,0.0254f,0.9988f,0.0421f,1.5929f,0f,0.0421f,-0.9991f,0.0197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9997f,0.0254f,0.0008f,0.0239f,0.0254f,0.9992f,0.0301f,0.9372f,0f,0.0301f,-0.9995f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9997f,0.0254f,0f,0f,0.0254f,0.9997f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0633708373,"py":2.4898323812,"pz":0.9958947781,"ry":0.0614496654,"rx":2.4129218264}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args