# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9998f,0.0181f,0.0004f,0.0473f,0.0181f,0.9996f,0.0226f,2.62f,0f,0.0226f,-0.9997f,0.2214f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9998f,0.0181f,0.0004f,0.0423f,0.0181f,0.9996f,0.0226f,2.3388f,0f,0.0226f,-0.9997f,0.215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9998f,0.0181f,0.0004f,0.0423f,0.0181f,0.9996f,0.0226f,2.3433f,0f,0.0226f,-0.9997f,0.0198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9998f,0.0181f,0.0004f,0.0288f,0.0181f,0.9996f,0.0226f,1.5934f,0f,0.0226f,-0.9997f,0.0106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9998f,0.0181f,0.0003f,0.0169f,0.0181f,0.9997f,0.0162f,0.9373f,0f,0.0162f,-0.9999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9998f,0.0181f,0f,0f,0.0181f,0.9998f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0453402758,"py":2.5093059988,"pz":0.9690736959,"ry":0.0234227572,"rx":1.2960847024}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args