# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9999f,0.0106f,0.0001f,0.0278f,0.0106f,0.9999f,0.0086f,2.6232f,0f,0.0086f,-1f,0.2003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9999f,0.0106f,0.0001f,0.0248f,0.0106f,0.9999f,0.0086f,2.342f,0f,0.0086f,-1f,0.1979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9999f,0.0106f,0.0001f,0.0248f,0.0106f,0.9999f,0.0086f,2.3436f,0f,0.0086f,-1f,0.0026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9999f,0.0106f,0.0001f,0.0169f,0.0106f,0.9999f,0.0086f,1.5936f,0f,0.0086f,-1f,0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9999f,0.0106f,0.0001f,0.0099f,0.0106f,0.9999f,0.0061f,0.9374f,0f,0.0061f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9999f,0.0106f,0f,0f,0.0106f,0.9999f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0266905998,"py":2.5230447915,"pz":0.9494920032,"ry":0.0051834121,"rx":0.4899725838}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args