# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:entity_crown_piranha rig_hash set value 'd42c4915a3dc46007365ab244f30ebdc22df43c15c33e62cbb2aea39c67778c9'
scoreboard objectives add aj.medium_grow.frame dummy
scoreboard objectives add aj.medium_idle.frame dummy
scoreboard objectives add aj.large_grow.frame dummy
scoreboard objectives add aj.large_idle.frame dummy
scoreboard objectives add aj.attack.frame dummy