# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data merge entity @s {width:0,height:0,data:{original:{width:2.2,height:0.3}}}
data remove entity @s CustomName