# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0136f,-0.0051f,0.4999f,0.0051f,1.3114f,-0.0005f,0.0051f,-0.5f,0.1071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0121f,-0.0051f,0.4999f,0.0051f,1.1708f,-0.0005f,0.0051f,-0.5f,0.1056f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0121f,-0.0051f,0.4999f,0.0051f,1.1718f,-0.0005f,0.0051f,-0.5f,0.008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0082f,-0.0051f,0.4999f,0.0051f,0.7968f,-0.0005f,0.0051f,-0.5f,0.0081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5f,-0.0051f,0.0004f,-0.0048f,-0.0051f,0.4999f,0.0051f,0.4687f,-0.0005f,0.0051f,-0.5f,0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5f,-0.0051f,0.0004f,0f,-0.0051f,0.4999f,0.0051f,0f,-0.0005f,0.0051f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.0456405404,"rx":0.5824455295},"locator":{"px":-0.0133941018,"py":1.2607276955,"pz":0.4815801896,"ry":0.0456405404,"rx":0.5824455295}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args