# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4993f,0.027f,-0.0039f,0.0716f,0.0272f,0.4985f,-0.0272f,1.3137f,0.0024f,-0.0273f,-0.4992f,0.0218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4993f,0.027f,-0.0039f,0.064f,0.0272f,0.4985f,-0.0272f,1.1735f,0.0024f,-0.0273f,-0.4992f,0.0295f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4993f,0.027f,-0.0039f,0.0632f,0.0272f,0.4985f,-0.0272f,1.1682f,0.0024f,-0.0273f,-0.4992f,-0.068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4993f,0.027f,-0.0039f,0.043f,0.0272f,0.4985f,-0.0272f,0.7945f,0.0024f,-0.0273f,-0.4992f,-0.0436f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4993f,0.027f,-0.0039f,0.0253f,0.0272f,0.4985f,-0.0272f,0.4674f,0.0024f,-0.0273f,-0.4992f,-0.0256f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4993f,0.027f,-0.0039f,0f,0.0272f,0.4985f,-0.0272f,0f,0.0024f,-0.0273f,-0.4992f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.5579515231,"rx":-3.1156393951},"locator":{"px":0.0719143518,"py":1.2873609162,"pz":0.3988275324,"ry":359.5579515231,"rx":-3.1156393951}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args