# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.5f,0.004f,-0.0004f,0.0104f,0.004f,0.5f,-0.004f,1.3132f,0.0003f,-0.004f,-0.5f,0.0833f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.5f,0.004f,-0.0004f,0.0093f,0.004f,0.5f,-0.004f,1.1725f,0.0003f,-0.004f,-0.5f,0.0844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5f,0.004f,-0.0004f,0.0093f,0.004f,0.5f,-0.004f,1.1718f,0.0003f,-0.004f,-0.5f,-0.0132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5f,0.004f,-0.0004f,0.0063f,0.004f,0.5f,-0.004f,0.7968f,0.0003f,-0.004f,-0.5f,-0.0063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5f,0.004f,-0.0004f,0.0037f,0.004f,0.5f,-0.004f,0.4687f,0.0003f,-0.004f,-0.5f,-0.0037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5f,0.004f,-0.0004f,0f,0.004f,0.5f,-0.004f,0f,0.0003f,-0.004f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":359.9567808412,"rx":-0.455755501},"locator":{"px":0.0103587891,"py":1.2692739551,"pz":0.4586605777,"ry":359.9567808412,"rx":-0.455755501}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args