# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0466f,-0.0177f,0.4994f,0.0178f,1.3075f,-0.0015f,0.0177f,-0.4997f,0.1402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0417f,-0.0177f,0.4994f,0.0178f,1.1671f,-0.0015f,0.0177f,-0.4997f,0.1352f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0415f,-0.0177f,0.4994f,0.0178f,1.1705f,-0.0015f,0.0177f,-0.4997f,0.0376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0282f,-0.0177f,0.4994f,0.0178f,0.7959f,-0.0015f,0.0177f,-0.4997f,0.0282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.4997f,-0.0177f,0.0009f,-0.0166f,-0.0177f,0.4994f,0.0178f,0.4682f,-0.0015f,0.0177f,-0.4997f,0.0166f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.4997f,-0.0177f,0.0009f,0f,-0.0177f,0.4994f,0.0178f,0f,-0.0015f,0.0177f,-0.4997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0.1050583984,"rx":2.0359485173},"locator":{"px":-0.0456587186,"py":1.2473832611,"pz":0.5133064236,"ry":0.1050583984,"rx":2.0359485173}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args