# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(entity_hitbox) positioned ^0 ^0 ^0 rotated ~0 ~0 run function aj:entity_piranha/animations/attack/zzz/frames/32_locator_entity_hitbox
execute positioned ^0 ^1.6875 ^0.625 rotated ~0 ~0 run function aj:entity_piranha/animations/attack/zzz/frames/32_locator_locator
execute run function aj:entity_piranha/animations/attack/zzz/frames/32_function_keyframe