# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9999f,-0.0128f,-0.0001f,-0.0224f,-0.0128f,0.9999f,0.0086f,1.7488f,0f,0.0086f,-1f,0.1335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9999f,-0.0128f,-0.0001f,-0.02f,-0.0128f,0.9999f,0.0086f,1.5613f,0f,0.0086f,-1f,0.1319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9999f,-0.0128f,-0.0001f,-0.02f,-0.0128f,0.9999f,0.0086f,1.5624f,0f,0.0086f,-1f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9999f,-0.0128f,-0.0001f,-0.0136f,-0.0128f,0.9999f,0.0086f,1.0624f,0f,0.0086f,-1f,0.0027f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9999f,-0.0128f,-0.0001f,-0.008f,-0.0128f,0.9999f,0.0061f,0.6249f,0f,0.0061f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9999f,-0.0128f,0f,0f,-0.0128f,0.9999f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0215504591,"py":1.6819859238,"pz":0.6329946688,"ry":359.993722233,"rx":0.4899597847}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args