# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9995f,0.0322f,0.0021f,0.0562f,0.0323f,0.9973f,0.0659f,1.7389f,0f,0.0659f,-0.9978f,0.1907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9995f,0.0322f,0.0021f,0.0502f,0.0323f,0.9973f,0.0659f,1.5519f,0f,0.0659f,-0.9978f,0.1783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9995f,0.0322f,0.0021f,0.0505f,0.0323f,0.9973f,0.0659f,1.5605f,0f,0.0659f,-0.9978f,0.0484f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9995f,0.0322f,0.0021f,0.0343f,0.0323f,0.9973f,0.0659f,1.0615f,0f,0.0659f,-0.9978f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9995f,0.0323f,0.0015f,0.0202f,0.0323f,0.9984f,0.0471f,0.6247f,0f,0.0471f,-0.9989f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9995f,0.0323f,0f,0f,0.0323f,0.9995f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.0531460543,"py":1.6435921375,"pz":0.6854529093,"ry":0.122340969,"rx":3.7780225497}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args