# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9996f,-0.0298f,-0.0009f,-0.0521f,-0.0298f,0.9991f,0.0317f,1.7448f,0f,0.0318f,-0.9995f,0.1567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9996f,-0.0298f,-0.0009f,-0.0465f,-0.0298f,0.9991f,0.0317f,1.5575f,0f,0.0318f,-0.9995f,0.1507f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9996f,-0.0298f,-0.0009f,-0.0466f,-0.0298f,0.9991f,0.0317f,1.5616f,0f,0.0318f,-0.9995f,0.0206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9996f,-0.0298f,-0.0009f,-0.0317f,-0.0298f,0.9991f,0.0317f,1.0619f,0f,0.0318f,-0.9995f,0.0099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9996f,-0.0298f,-0.0007f,-0.0187f,-0.0298f,0.9993f,0.0227f,0.6247f,0f,0.0227f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9996f,-0.0298f,0f,0f,-0.0298f,0.9996f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0497510806,"py":1.6664798504,"pz":0.6544601996,"ry":359.9456716688,"rx":1.8191892217}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args