# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.entity_piranha.animation.small_grow.playing] run function aj:entity_piranha/animations/small_grow/zzz/on_tick
execute if entity @s[tag=aj.entity_piranha.animation.small_idle.playing] run function aj:entity_piranha/animations/small_idle/zzz/on_tick
execute if entity @s[tag=aj.entity_piranha.animation.medium_grow.playing] run function aj:entity_piranha/animations/medium_grow/zzz/on_tick
execute if entity @s[tag=aj.entity_piranha.animation.medium_idle.playing] run function aj:entity_piranha/animations/medium_idle/zzz/on_tick
execute if entity @s[tag=aj.entity_piranha.animation.large_grow.playing] run function aj:entity_piranha/animations/large_grow/zzz/on_tick
execute if entity @s[tag=aj.entity_piranha.animation.large_idle.playing] run function aj:entity_piranha/animations/large_idle/zzz/on_tick
function aj:entity_piranha/root/zzz/0 with storage animated_java:temp entry.data.uuids_by_name