# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.7748f,-0.0452f,0f,-0.0791f,-0.0452f,0.7748f,0f,1.3559f,0f,0f,-0.7761f,0.097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.7748f,-0.0452f,0f,-0.0707f,-0.0452f,0.7748f,0f,1.2106f,0f,0f,-0.7761f,0.097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.7748f,-0.0452f,0f,-0.0707f,-0.0452f,0.7748f,0f,1.2106f,0f,0f,-0.7761f,-0.004f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.7748f,-0.0452f,0f,-0.048f,-0.0452f,0.7748f,0f,0.8232f,0f,0f,-0.7761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.7748f,-0.0452f,0f,-0.0283f,-0.0452f,0.7748f,0f,0.4843f,0f,0f,-0.7761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.7748f,-0.0452f,0f,0f,-0.0452f,0.7748f,0f,0f,0f,0f,-0.7761f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0763050518,"py":1.3074862442,"pz":0.485078125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args