# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.8036f,-0.0241f,0f,-0.0422f,-0.0241f,0.8036f,0f,1.4064f,0f,0f,-0.804f,0.1005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.8036f,-0.0241f,0f,-0.0377f,-0.0241f,0.8036f,0f,1.2557f,0f,0f,-0.804f,0.1005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.8036f,-0.0241f,0f,-0.0377f,-0.0241f,0.8036f,0f,1.2557f,0f,0f,-0.804f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.8036f,-0.0241f,0f,-0.0256f,-0.0241f,0.8036f,0f,0.8539f,0f,0f,-0.804f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.8036f,-0.0241f,0f,-0.0151f,-0.0241f,0.8036f,0f,0.5023f,0f,0f,-0.804f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.8036f,-0.0241f,0f,0f,-0.0241f,0.8036f,0f,0f,0f,0f,-0.804f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0406934745,"py":1.3561395959,"pz":0.5025,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args