# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9156f,0.0667f,0f,0.1167f,0.0667f,0.9156f,0f,1.6023f,0f,0f,-0.918f,0.1148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9156f,0.0667f,0f,0.1042f,0.0667f,0.9156f,0f,1.4306f,0f,0f,-0.918f,0.1148f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9156f,0.0667f,0f,0.1042f,0.0667f,0.9156f,0f,1.4306f,0f,0f,-0.918f,-0.0048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9156f,0.0667f,0f,0.0709f,0.0667f,0.9156f,0f,0.9728f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9156f,0.0667f,0f,0.0417f,0.0667f,0.9156f,0f,0.5722f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9156f,0.0667f,0f,0f,0.0667f,0.9156f,0f,0f,0f,0f,-0.918f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.1125450431,"py":1.5450313521,"pz":0.57375,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args