# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.9623f,0.0842f,0f,0.1473f,0.0842f,0.9623f,0f,1.6841f,0f,0f,-0.966f,0.1208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.9623f,0.0842f,0f,0.1316f,0.0842f,0.9623f,0f,1.5036f,0f,0f,-0.966f,0.1208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.9623f,0.0842f,0f,0.1316f,0.0842f,0.9623f,0f,1.5036f,0f,0f,-0.966f,-0.005f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9623f,0.0842f,0f,0.0895f,0.0842f,0.9623f,0f,1.0225f,0f,0f,-0.966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.9623f,0.0842f,0f,0.0526f,0.0842f,0.9623f,0f,0.6015f,0f,0f,-0.966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.9623f,0.0842f,0f,0f,0.0842f,0.9623f,0f,0f,0f,0f,-0.966f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":0.1420747551,"py":1.6239218822,"pz":0.60375,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args