# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.5336f,-0.0203f,0f,-0.0355f,-0.0203f,0.5336f,0f,0.9338f,0f,0f,-0.534f,0.0668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.5336f,-0.0203f,0f,-0.0317f,-0.0203f,0.5336f,0f,0.8338f,0f,0f,-0.534f,0.0668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5336f,-0.0203f,0f,-0.0317f,-0.0203f,0.5336f,0f,0.8338f,0f,0f,-0.534f,-0.0028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5336f,-0.0203f,0f,-0.0216f,-0.0203f,0.5336f,0f,0.567f,0f,0f,-0.534f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5336f,-0.0203f,0f,-0.0127f,-0.0203f,0.5336f,0f,0.3335f,0f,0f,-0.534f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5336f,-0.0203f,0f,0f,-0.0203f,0.5336f,0f,0f,0f,0f,-0.534f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0342668955,"py":0.9004732342,"pz":0.33375,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args