# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function aj:entity_piranha/animations/large_idle/play
scoreboard players set @s entity.strength 2
function entity:interaction/spawn {height: 2, width: 1}