# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.5554f,-0.0363f,0f,-0.0635f,-0.0363f,0.5554f,0f,0.972f,0f,0f,-0.5566f,0.0696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.5554f,-0.0363f,0f,-0.0567f,-0.0363f,0.5554f,0f,0.8679f,0f,0f,-0.5566f,0.0696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.5554f,-0.0363f,0f,-0.0567f,-0.0363f,0.5554f,0f,0.8679f,0f,0f,-0.5566f,-0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5554f,-0.0363f,0f,-0.0386f,-0.0363f,0.5554f,0f,0.5902f,0f,0f,-0.5566f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.5554f,-0.0363f,0f,-0.0227f,-0.0363f,0.5554f,0f,0.3472f,0f,0f,-0.5566f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.5554f,-0.0363f,0f,0f,-0.0363f,0.5554f,0f,0f,0f,0f,-0.5566f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.0612546142,"py":0.9373052695,"pz":0.347890625,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args