# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.6327f,-0.0823f,0f,-0.144f,-0.0823f,0.6327f,0f,1.1072f,0f,0f,-0.638f,0.0797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.6327f,-0.0823f,0f,-0.1286f,-0.0823f,0.6327f,0f,0.9885f,0f,0f,-0.638f,0.0797f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.6327f,-0.0823f,0f,-0.1286f,-0.0823f,0.6327f,0f,0.9885f,0f,0f,-0.638f,-0.0033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6327f,-0.0823f,0f,-0.0875f,-0.0823f,0.6327f,0f,0.6722f,0f,0f,-0.638f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.6327f,-0.0823f,0f,-0.0514f,-0.0823f,0.6327f,0f,0.3954f,0f,0f,-0.638f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6327f,-0.0823f,0f,0f,-0.0823f,0.6327f,0f,0f,0f,0f,-0.638f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.1388981618,"py":1.0676275995,"pz":0.39875,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args