# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone2) {transformation: [-0.6614f,-0.0871f,0f,-0.1524f,-0.0871f,0.6614f,0f,1.1575f,0f,0f,-0.6671f,0.0834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone3) {transformation: [-0.6614f,-0.0871f,0f,-0.1361f,-0.0871f,0.6614f,0f,1.0335f,0f,0f,-0.6671f,0.0834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone1) {transformation: [-0.6614f,-0.0871f,0f,-0.1361f,-0.0871f,0.6614f,0f,1.0335f,0f,0f,-0.6671f,-0.0035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6614f,-0.0871f,0f,-0.0925f,-0.0871f,0.6614f,0f,0.7028f,0f,0f,-0.6671f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone4) {transformation: [-0.6614f,-0.0871f,0f,-0.0544f,-0.0871f,0.6614f,0f,0.4134f,0f,0f,-0.6671f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(root) {transformation: [-0.6614f,-0.0871f,0f,0f,-0.0871f,0.6614f,0f,0f,0f,0f,-0.6671f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{},"locators":{"entity_hitbox":{"px":0,"py":0,"pz":0,"ry":0,"rx":0},"locator":{"px":-0.1469429201,"py":1.1161422897,"pz":0.416953125,"ry":0,"rx":0}}}
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args