# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.entity_crown_piranha.animation.medium_grow.playing
tag @s remove aj.entity_crown_piranha.animation.medium_idle.playing
tag @s remove aj.entity_crown_piranha.animation.large_grow.playing
tag @s remove aj.entity_crown_piranha.animation.large_idle.playing
tag @s remove aj.entity_crown_piranha.animation.attack.playing